Add Particles class
zeshunzong/drake pull request #10
Opened 2023-10-08 19:03 UTC by zeshunzong

2023-10-08 19:13 UTC, zeshunzong reviewed
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10#-:-NgFfGjR0PwiL0kVFdIN:bk7giky)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/particles.h` line 50 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFfNfg8fDfHSd39K35:-NgFfNfg8fDfHSd39K36:b9t0r5u) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L50)):*
> ```objc
>   // after calling Reorder() will be [p2; p0; p1]
>   // @pre new_order is a permutation of [0, ..., num_particles-1]
>   void Reorder(const std::vector<size_t>& new_order);
> ```

Question here. The goal is to sort particles based on lexicographically ordered grid nodes. 
I can think of several ways to do that.
The one I am choosing rn is to supply a permutation new_order externally (should be computed in MpmTransfer), and then apply the permutation to all std::vectors in Particles class, and do so in place. So num_std_vectors * O(n) in time, and no extra space required.

Alternatively, one can create Particle class and make Particles as std::vector<Particle>, and maybe do a sorting of the std::vector<Particle>. 

I think they should have the overall same complexity. The current version seems more readable to me.
___
*[`multibody/mpm/particles.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFgsehAD7RpzjSs0Ix:-NgFgsei4qKVLwljYvWn:b-x03t4g) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L56)):*
> ```objc
>    * velocity.
>    */
>   void AdvectParticles(double dt) {
> ```

I think we don't difftest on dt, do we?
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgFh594ESkxPlCzWW_4:b-rw7iup) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
> ```objc
>    * @pre node_local < 27
>    */
>   void SetWeightAtParticleAndNeighborNode(size_t p, size_t node_local,
> ```

Any naming suggestions?
___
*[`multibody/mpm/particles.h` line 232 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh9SWBqv4TEVmQDHm:-NgFh9SWBqv4TEVmQDHn:b-rw7iup) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L232)):*
> ```objc
>    * @note the stored Nᵢ(xₚ) is meaningless when xₚ changes.
>    */
>   const T& GetWeightAtParticleAndNeighborNode(size_t p,
> ```

Any naming suggestions?
___
*[`multibody/mpm/particles.h` line 274 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFhCrOET-XPI49hkac:-NgFhCrOET-XPI49hkad:b-rw7iup) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L274)):*
> ```objc
>   // ∈ [27 neighbor grid nodes].
>   std::vector<std::array<size_t, 27>> neighbor_grid_nodes_global_indices_{};
>   std::vector<std::array<T, 27>> w_ip_neighbor_nodes_{};
> ```

Any naming suggestions?


<!-- Sent from Reviewable.io -->

2023-10-09 20:10 UTC, xuchenhan-tri requested changes
I made a pass through the non-test files. I have some concerns about your strategy for reordering. PTAL.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10#-:-NgL3-4kBMBGMDrks0Zl:b-hfjna8)* status: 3 of 4 files reviewed, 12 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKmcKb71F0ONVVs-zv:-NgKmcKb71F0ONVVs-zw:b-4kx7cu) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/BUILD.bazel#L11)):*
> ```Starlark
>     "@drake//tools/vector_gen:vector_gen.bzl",
>     "drake_cc_vector_gen_library",
> )
> ```

nit unused



_Code quote:_
```Starlark
load(
    "@drake//tools/vector_gen:vector_gen.bzl",
    "drake_cc_vector_gen_library",
)
```
___
*[`multibody/mpm/particles.h` line 36 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKr8jF2VrcEg47K4Gv:-NgKr8jF2VrcEg47K4Gw:bmqkarp) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L36)):*
> ```objc
>    * This will be used sampling info is loaded externally.
>    */
>   explicit Particles(size_t num_particles_);
> ```

nit style



_Suggestion:_
```objc
explicit Particles(size_t num_particles);
```
___
*[`multibody/mpm/particles.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKrOFPE7BHZUQFUCpX:-NgKrOFPE7BHZUQFUCpY:b-1dnmg3) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L38)):*
> ```objc
>   explicit Particles(size_t num_particles_);
> 
>   // Adds (appends) a particle into Particles with given properties.
> ```

Is the mixed use of doxygen vs. non-doxygen comment styles intentional? If so, why?
___
*[`multibody/mpm/particles.h` line 50 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFfNfg8fDfHSd39K35:-NgL2vvK4lBhkgvCXrnC:b-bx61ez) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L50)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Question here. The goal is to sort particles based on lexicographically ordered grid nodes. 
I can think of several ways to do that.
The one I am choosing rn is to supply a permutation new_order externally (should be computed in MpmTransfer), and then apply the permutation to all std::vectors in Particles class, and do so in place. So num_std_vectors * O(n) in time, and no extra space required.

Alternatively, one can create Particle class and make Particles as std::vector<Particle>, and maybe do a sorting of the std::vector<Particle>. 

I think they should have the overall same complexity. The current version seems more readable to me.
</blockquote></details>

See my comment in the cc file
___
*[`multibody/mpm/particles.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFgsehAD7RpzjSs0Ix:-NgKmlkwCv-o63JaXcxV:b-ta29mk) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L56)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

I think we don't difftest on dt, do we?
</blockquote></details>

double dt is fine.
___
*[`multibody/mpm/particles.h` line 82 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKoDmg051LIkiS8UBY:-NgKoDmg051LIkiS8UBZ:bn9dq5w) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L82)):*
> ```objc
> 
>   /**
>    * Returns the position of p_th particle.
> ```

typo

Ditto throughout file



_Suggestion:_
```objc
p-th
```
___
*[`multibody/mpm/particles.h` line 83 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKn4ehCPI9BqQR7632:-NgKn4ehCPI9BqQR7633:b9gk4sk) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L83)):*
> ```objc
>   /**
>    * Returns the position of p_th particle.
>    * @pre 0 <= p < num_particles_
> ```

nit don't show private data members in doxygen comment. Doxygen comments are for users of your class. They don't know about  and don't care about your private data member.

Ditto below.



_Suggestion:_
```objc
* @pre 0 <= p < num_particles()
```
___
*[`multibody/mpm/particles.h` line 120 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnQJ36pyUtOVRisPP:-NgKnQJ36pyUtOVRisPQ:bf2qs6g) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L120)):*
> ```objc
>    * Returns the deformation gradient of p_th particle.
>    * @pre 0 <= p < num_particles_
>    * @note one must know beforehand if the data stored is F_trial or F_elastic.
> ```

nit this documentation can be improved. It's unclear to a potential reader what you mean by `F_trial` and `F_elastic`. Also, it's unclear to me why this can return either the trial and the elastic deformation gradient.



_Code quote:_
```objc
* @note one must know beforehand if the data stored is F_trial or F_elastic.
```
___
*[`multibody/mpm/particles.h` line 130 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnp9VDBA0w2wy1cD2:-NgKnp9VDBA0w2wy1cD3:b-4djur3) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L130)):*
> ```objc
>    * Returns the B_matrix of p_th particle. B_matrix is part of the affine
>    * momentum matrix C as
>    * v_i = v_p + C_p (x_i - x_p) = v_p + B_p D_p^-1 (x_i - x_p).
> ```

It's impossible for a reader to understand what you mean by these notations. You should at least provide a reference.



_Code quote:_
```objc
v_i = v_p + C_p (x_i - x_p) = v_p + B_p D_p^-1 (x_i - x_p).
```
___
*[`multibody/mpm/particles.h` line 181 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKuG7nA4_bpmP-opyG:-NgKuG7o9k8BayRv7_6q:byb4z9d) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L181)):*
> ```objc
>    * @pre node_local < 27
>    * @pre node_global < sparse_grid.num_active_nodes()
>    */
> ```

This documentation is not very helpful. Currently it discusses a few concepts that have never been introduced before like a sparse grid, a local and global indexing of such grid, and a magic number of 27. I would have no idea what to do with this function if I'm not already deeply involved in the development and know what you mean by these secret codes.

One way to improve the documentation here is to first give an overview of the relationship between the particles and the (I image soon-to-be-added) MPM grid and discuss how the particles are indexed based on the grid nodes they are associated with. Potentially this can happen in the class documentation.



_Code quote:_
```objc
  /**
   * For the node_local-th neighbor (out of a total of 27) grid node of particle
   * p, stores its global index in sparse_grid given by node_global.
   * @pre p < num_particles_
   * @pre node_local < 27
   * @pre node_global < sparse_grid.num_active_nodes()
   */
```
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgKwMTjA9KQpmE4-f4f:bslneff) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Any naming suggestions?
</blockquote></details>

I'm fine with the current name, but documentation can be improved like I said in an earlier thread.

Also I need to see how you intend to use these weights to determine whether it's better to a have separate abstraction for the weights and weight gradients for a particle.
___
*[`multibody/mpm/particles.h` line 232 at r1 [...]

2023-10-09 20:20 UTC, zeshunzong commented
*[`multibody/mpm/particles.cc` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgL1vzO-Gn8BVv1_FR2:-NgL57Pt6aQmfhAtkE6R:bisdal8) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

A few questions/comments about this function:
1. Why are only part of the data reordered? In particular, `neighbor_grid_nodes_global_indices_`, `w_ip_neighbor_nodes_` and `dw_ip_neighbor_nodes_` are not reordered.
2. IIRC, this is different from what Yimin used in his implementation. What do you gain from using a new implementation over a well-tested existing implementation?
3. The time complexity of this algorithm is worst case quadratic. It can kill your performance when you have large number of particles.
</blockquote></details>

Let's talk about complexity first. ind = new_order[ind] is at most quadratic. Swapping is O(n)


<!-- Sent from Reviewable.io -->

2023-10-09 20:35 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKmcKb71F0ONVVs-zv:-NgL6xAVATJJelVDhYtB:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/BUILD.bazel#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 36 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKr8jF2VrcEg47K4Gv:-NgL6s0eEoa-DCWV3QhB:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L36)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit style
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKrOFPE7BHZUQFUCpX:-NgL7-DX8qM0VkMI7idw:b22hpk9) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L38)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is the mixed use of doxygen vs. non-doxygen comment styles intentional? If so, why?
</blockquote></details>

When there is a TODO, I don't know what to do. Functions without TODOs are commented in doxygen
___
*[`multibody/mpm/particles.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFgsehAD7RpzjSs0Ix:-NgL7H9qDtWUzGaZjD5B:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

double dt is fine.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 82 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKoDmg051LIkiS8UBY:-NgL7RBK9qYPoLNd7_9t:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L82)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo

Ditto throughout file
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 83 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKn4ehCPI9BqQR7632:-NgL85ve7I3xkSBgcdXi:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit don't show private data members in doxygen comment. Doxygen comments are for users of your class. They don't know about  and don't care about your private data member.

Ditto below.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgL8Eyn8EJrIwVSk_vx:bswmoej) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm fine with the current name, but documentation can be improved like I said in an earlier thread.

Also I need to see how you intend to use these weights to determine whether it's better to a have separate abstraction for the weights and weight gradients for a particle.
</blockquote></details>

Just a heads-up. When we compute the contact Jacobian, this is computed for each contact pair (i.e. each MPM particle in contact). In forming the Jacobian, one gets that particle index and then grab the weights for this particular particle.
___
*[`multibody/mpm/particles.h` line 232 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh9SWBqv4TEVmQDHm:-NgL8coq8kcKdGS9DPgY:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L232)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Looks fine to me
</blockquote></details>

done
___
*[`multibody/mpm/particles.cc` line 69 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKlOnS3LOPAEgkKKzN:-NgL6lo4ADIUUoe2kjhV:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

either move the data in place or pass by const reference.
</blockquote></details>

done
___
*[`multibody/mpm/particles.cc` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKle09Ap1mODxEHNTZ:-NgL6mlo46gJ4MMD-bhH:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-09 21:39 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKmcKb71F0ONVVs-zv:-NgLNLaIBqwMeujdIDIK:b-60eb3n) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/BUILD.bazel#L11)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

I'm not see the changes. Did you push?
___
*[`multibody/mpm/particles.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKrOFPE7BHZUQFUCpX:-NgLM00B3otSkNBQ9oyQ:b-eofmoc) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L38)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

When there is a TODO, I don't know what to do. Functions without TODOs are commented in doxygen
</blockquote></details>

For 95% of the problem you are running into, chances are people before you have run into the same problem. Searching in the codebase for precedence is a good first step in trying to solve the problem.

https://github.com/RobotLocomotion/drake/blob/eb4a10b89e501da7aa17f173cc01c6b6feed46cc/multibody/plant/multibody_plant.h#L340

Same comment for the function below.
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgLMZtuEZkB_pkvnj10:b-qgg00z) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Just a heads-up. When we compute the contact Jacobian, this is computed for each contact pair (i.e. each MPM particle in contact). In forming the Jacobian, one gets that particle index and then grab the weights for this particular particle.
</blockquote></details>

Would it make sense to have a struct/class for the weights and the weight gradients? That struct can also provide utilities for interpolation.
___
*[`multibody/mpm/particles.cc` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgL1vzO-Gn8BVv1_FR2:-NgLMqWP57L1IJpLsi5l:b-gq7bsq) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L24)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Let's talk about complexity first. ind = new_order[ind] is at most quadratic. Swapping is O(n)
</blockquote></details>

Yes I understand the complexity

Your inner while loop is worst-case O(n) and without a formal proof I think the average-case is also O(n). I have a quadratic algorithm in the inner loop particle operation concerns me. Did you use this for the demos you produced?


<!-- Sent from Reviewable.io -->

2023-10-14 06:09 UTC, zeshunzong reviewed
Made changes based on comments. The test basically only validates the correctness of the two Reorder methods.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10#-:-NggnGFzA6qIV3dU-8Kv:bvf2hyi)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKmcKb71F0ONVVs-zv:-NgfhUhf8tAFDnVq-8vC:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/BUILD.bazel#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not see the changes. Did you push?
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKrOFPE7BHZUQFUCpX:-Nggmx9xErUQuxQT1et6:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L38)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

For 95% of the problem you are running into, chances are people before you have run into the same problem. Searching in the codebase for precedence is a good first step in trying to solve the problem.

https://github.com/RobotLocomotion/drake/blob/eb4a10b89e501da7aa17f173cc01c6b6feed46cc/multibody/plant/multibody_plant.h#L340

Same comment for the function below.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 50 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFfNfg8fDfHSd39K35:-Ngg6kWDEEHPIdXpR-ob:b-hqal0e) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L50)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

See my comment in the cc file
</blockquote></details>

Done Allow two versions temporarily, per discussion.
___
*[`multibody/mpm/particles.h` line 120 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnQJ36pyUtOVRisPP:-NggjoOs3rntVCl3TTiw:b847zxh) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L120)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this documentation can be improved. It's unclear to a potential reader what you mean by `F_trial` and `F_elastic`. Also, it's unclear to me why this can return either the trial and the elastic deformation gradient.
</blockquote></details>

I don't indeed to have two attributes, one storing F_trial and the other F_elastic. The ReturnMap(F) in constitutive model is also changing F in place. This is a simple getter, whether it is F_trial or F_elastic depends on whether you have applied returnmap.

Or we can store both F_trial and F_elastic. Maybe that will be more readable?

Any suggestions?
___
*[`multibody/mpm/particles.h` line 130 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnp9VDBA0w2wy1cD2:-NggjmCs82-REv9VfkWH:b-b6m0we) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's impossible for a reader to understand what you mean by these notations. You should at least provide a reference.
</blockquote></details>

Done reference added
___
*[`multibody/mpm/particles.h` line 181 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKuG7nA4_bpmP-opyG:-NggjgZ85OgW_oTyIC8s:b-t2z3p6) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L181)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This documentation is not very helpful. Currently it discusses a few concepts that have never been introduced before like a sparse grid, a local and global indexing of such grid, and a magic number of 27. I would have no idea what to do with this function if I'm not already deeply involved in the development and know what you mean by these secret codes.

One way to improve the documentation here is to first give an overview of the relationship between the particles and the (I image soon-to-be-added) MPM grid and discuss how the particles are indexed based on the grid nodes they are associated with. Potentially this can happen in the class documentation.
</blockquote></details>

Temporarily removed. See the new proposed implementation below
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgghnSBBMeEGqe6bc8_:bg02e1f) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Would it make sense to have a struct/class for the weights and the weight gradients? That struct can also provide utilities for interpolation.
</blockquote></details>

What about this?

Define class InterpolationWeights (associated with each particle) {
 array<int,27> neighbor_node_indices_;
 array<T, 27> weights_;
array < , 27> weight_graidents_;

// maybe can also put some interpolation utilities here
}

Then this Particles class stores an attribute std::vector<InterpolationWeights>.

In that way there is no need to explain the magic number 27 in this class (and if one thinks about this abstractly, one indeed should not). std::vector<InterpolationWeights> being an attribute to the Particles class also allows a convenient and readable way to form contact Jacobian.

I am going to temporarily remove all 27-related stuff in this PR. If you agree with the this proposal, I will implement this in next PR.
___
*[`multibody/mpm/particles.h` line 274 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFhCrOET-XPI49hkac:-Nggj_C641R8aw3UxBwf:b-gy4c0b) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L274)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

How about just `weights_` and `weight_graidents_`
</blockquote></details>

Temporarily removed. See the new proposed implementation
___
*[`multibody/mpm/particles.cc` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgL1vzO-Gn8BVv1_FR2:-Nggn6o15FQm3M5IKI2V:bqnpoas) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes I understand the complexity

Your inner while loop is worst-case O(n) and without a formal proof I think the average-case is also O(n). I have a quadratic algorithm in the inner loop particle operation concerns me. Did you use this for the demos you produced?
</blockquote></details>

done per discussion
___
*[`multibody/mpm/particles.cc` line 69 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKlOnS3LOPAEgkKKzN:-NgfocLQDiRYCK0fUqYJ:bucgu12) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.cc#L69)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

passed by const reference now


<!-- Sent from Reviewable.io -->

2023-10-16 21:52 UTC, xuchen-han reviewed
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/particles.h` line 120 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnQJ36pyUtOVRisPP:-NguSZGy2qkTlQmES38Q:b-tnp7j8) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L120)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

I don't indeed to have two attributes, one storing F_trial and the other F_elastic. The ReturnMap(F) in constitutive model is also changing F in place. This is a simple getter, whether it is F_trial or F_elastic depends on whether you have applied returnmap.

Or we can store both F_trial and F_elastic. Maybe that will be more readable?

Any suggestions?
</blockquote></details>

This feels like a design defect to me. We are going to treat Particles as a state in the context (even though deformation gradient is more like a cache entry). In a single context, the state/cache entry value should be the same no matter when and where you query it.

Therefore, I think it's better that we store both F_trial and FE in particles.
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NguNF9q17Uq9wQp0ipi:b-78atgt) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

What about this?

Define class InterpolationWeights (associated with each particle) {
 array<int,27> neighbor_node_indices_;
 array<T, 27> weights_;
array < , 27> weight_graidents_;

// maybe can also put some interpolation utilities here
}

Then this Particles class stores an attribute std::vector<InterpolationWeights>.

In that way there is no need to explain the magic number 27 in this class (and if one thinks about this abstractly, one indeed should not). std::vector<InterpolationWeights> being an attribute to the Particles class also allows a convenient and readable way to form contact Jacobian.

I am going to temporarily remove all 27-related stuff in this PR. If you agree with the this proposal, I will implement this in next PR.
</blockquote></details>

I'll need to see the actual design to say definitively, but so far this sgtm.
___
*[`multibody/mpm/particles.h` line 220 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguNZu8CkxZ_Wi_l4o3:-NguNZu8CkxZ_Wi_l4o4:b-xyz97r) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.h#L220)):*
> ```objc
> 
>   // for reorder only
>   std::vector<T> temporary_scalar_field_{};
> ```

BTW, you can roll these three members into a `Scratch` struct and in the struct documentation you can elaborate on why these are needed. Without understanding the back story, it'd be hard to figure out why these are needed "for reorder only".
___
*[`multibody/mpm/particles.cc` line 64 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguOD527gjv7HBw1M9C:-NguOD527gjv7HBw1M9D:bc8f1v8) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.cc#L64)):*
> ```cpp
>   DRAKE_DEMAND((new_order.size()) == num_particles_);
> 
>   temporary_scalar_field_ = masses_;
> ```

BTW, following the comment from above: the struct can also take care of the boilerplate of reordering these different data types.
```
void Scratch::Reorder(const std::vector<size_t>& new_order, std::vector<Vector3<T>>* data) {
   for (size_t i = 0; i < size_; ++i) {
       vec_scratch[i] = *data[new_order[i]];
   }
   data->swap(vec_scratch);
}
```

___
*[`multibody/mpm/test/particles_test.cc` line 47 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguQOEa1oTMx8wNbufG:-NguQOEa1oTMx8wNbufH:b-km3yyd) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L47)):*
> ```cpp
> 
>   // getters for a single particle
>   for (size_t p = 0; p < 3; p++) {
> ```

nit preincrement, ditto throughout
___
*[`multibody/mpm/test/particles_test.cc` line 82 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguRArtD_rmTyFS4Sdh:-NguRArtD_rmTyFS4Sdi:bz6g28u) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L82)):*
> ```cpp
> }
> 
> void CheckReorder(const Particles<double>& particles,
> ```

minor, while I understand this is test code within a dev branch, I think we can still tidy things up a bit here to help with reducing duplication and improving readability. 

1. `CheckReorder` and `CheckReorder2` can easily be combined into a single function with a signature like `void CheckReordering(const Particles& particles, const Particles& reordered_particles, const std::vector<size_t>& ordering)`.
2.  Currently the correctness of the test relies heavily on **exactly** how you initialize the particles. It doesn't need to be that way. But if you are somehow attached to this magic number testing. You should clarify the testing strategy right before the line `GTEST_TEST(ParticlesTest, TestReorder)`.
___
*[`multibody/mpm/test/particles_test.cc` line 162 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguR59v9YUb3kbHspWr:-NguR59v9YUb3kbHspWs:b-9aomzw) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L162)):*
> ```cpp
>   }
> 
>   // The two Reorder methods should be mathematically correct.
> ```

nit, dead comment?


<!-- Sent from Reviewable.io -->

2023-10-16 23:38 UTC, zeshunzong reviewed
I also changed the signature for returnmapping in constitutive models. 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10#-:-Nguqhw9CSbUQ4f6o-Hi:b-dj234h)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/particles.h` line 120 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgKnQJ36pyUtOVRisPP:-NguUz743MoQ27de1Xmp:b-dx0ss3) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L120)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This feels like a design defect to me. We are going to treat Particles as a state in the context (even though deformation gradient is more like a cache entry). In a single context, the state/cache entry value should be the same no matter when and where you query it.

Therefore, I think it's better that we store both F_trial and FE in particles.
</blockquote></details>

Done I agreed. In fact I am always in favor of this while most MPM codebase I have seen just stores F. 
___
*[`multibody/mpm/particles.h` line 205 at r1](https://reviewable.io/reviews/zeshunzong/drake/10#-NgFh594ESkxPlCzWW_3:-NgubnYs-sK13IsmVLoM:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b25468e44b0651b1d2f99984fc4183d3821b93af/multibody/mpm/particles.h#L205)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'll need to see the actual design to say definitively, but so far this sgtm.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 220 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguNZu8CkxZ_Wi_l4o3:-NguqUju2t0JDCPal1jc:b-nujmlu) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.h#L220)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, you can roll these three members into a `Scratch` struct and in the struct documentation you can elaborate on why these are needed. Without understanding the back story, it'd be hard to figure out why these are needed "for reorder only".
</blockquote></details>

I added a TODO. Let's defer until we pick a reorder method
___
*[`multibody/mpm/particles.cc` line 64 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguOD527gjv7HBw1M9C:-Nguqaxx4i7ShoaT0TON:b-mtrt55) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.cc#L64)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, following the comment from above: the struct can also take care of the boilerplate of reordering these different data types.
```
void Scratch::Reorder(const std::vector<size_t>& new_order, std::vector<Vector3<T>>* data) {
   for (size_t i = 0; i < size_; ++i) {
       vec_scratch[i] = *data[new_order[i]];
   }
   data->swap(vec_scratch);
}
```

</blockquote></details>

done see above
___
*[`multibody/mpm/test/particles_test.cc` line 47 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguQOEa1oTMx8wNbufG:-NgucLOa99VWVOvYuBq6:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit preincrement, ditto throughout
</blockquote></details>

done
___
*[`multibody/mpm/test/particles_test.cc` line 82 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguRArtD_rmTyFS4Sdh:-NgugFBp-Awibnm-F_5G:b-x26j58) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L82)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, while I understand this is test code within a dev branch, I think we can still tidy things up a bit here to help with reducing duplication and improving readability. 

1. `CheckReorder` and `CheckReorder2` can easily be combined into a single function with a signature like `void CheckReordering(const Particles& particles, const Particles& reordered_particles, const std::vector<size_t>& ordering)`.
2.  Currently the correctness of the test relies heavily on **exactly** how you initialize the particles. It doesn't need to be that way. But if you are somehow attached to this magic number testing. You should clarify the testing strategy right before the line `GTEST_TEST(ParticlesTest, TestReorder)`.
</blockquote></details>

1 is done; 2, what other option do we have? Can use that when we finalize the reorder and rewrite the test.
___
*[`multibody/mpm/test/particles_test.cc` line 162 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguR59v9YUb3kbHspWr:-NgucPyw51mTX2qeKdGn:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L162)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, dead comment?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-17 00:29 UTC, xuchenhan-tri approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: all files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/particles.h` line 50 at r5](https://reviewable.io/reviews/zeshunzong/drake/10#-Ngv0Jwp3Bd6_0LqquGV:-Ngv0Jwp3Bd6_0LqquGW:btdn57u) ([raw file](https://github.com/zeshunzong/drake/blob/32500b0fa53542bc227b9ce6e41779ffe073a23d/multibody/mpm/particles.h#L50)):*
> ```objc
>   void AddParticle(const Vector3<T>& position, const Vector3<T>& velocity,
>                    const T& mass, const T& reference_volume,
>                    const Matrix3<T>& trial_deformation_gradient,
> ```

BTW, do we ever put anything here other than identity? If not, probably not worth putting them as parameters?
___
*[`multibody/mpm/particles.cc` line 64 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguOD527gjv7HBw1M9C:-Ngv0gYA45_B4PlfrDpH:bm3buke) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.cc#L64)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done see above
</blockquote></details>

Do you want to change to the swap implementation instead? A swap is constant time while a copy assign is linear.
___
*[`multibody/mpm/test/particles_test.cc` line 82 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguRArtD_rmTyFS4Sdh:-Ngv15kZ4Ke7T4YJBpCH:b-gjvic6) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L82)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

1 is done; 2, what other option do we have? Can use that when we finalize the reorder and rewrite the test.
</blockquote></details>

2. You could have just compared the data from `particles` and that from `reordered_particles` based on `ordering`. But this is fine too, just more brittle.


<!-- Sent from Reviewable.io -->

2023-10-17 07:22 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/particles.h` line 50 at r5](https://reviewable.io/reviews/zeshunzong/drake/10#-Ngv0Jwp3Bd6_0LqquGV:-NgwN6WEEEjXfENTYg1z:b-xmyhw1) ([raw file](https://github.com/zeshunzong/drake/blob/32500b0fa53542bc227b9ce6e41779ffe073a23d/multibody/mpm/particles.h#L50)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, do we ever put anything here other than identity? If not, probably not worth putting them as parameters?
</blockquote></details>

Done I am gonna pass on this, as the more fundamental question is whether do we start from rest shape. Let's bring this up again later. TODO added in code.
___
*[`multibody/mpm/particles.cc` line 64 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguOD527gjv7HBw1M9C:-NgwVr1K-o_YhXB42sxz:b-t0v78l) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/particles.cc#L64)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do you want to change to the swap implementation instead? A swap is constant time while a copy assign is linear.
</blockquote></details>

done changed
___
*[`multibody/mpm/test/particles_test.cc` line 82 at r4](https://reviewable.io/reviews/zeshunzong/drake/10#-NguRArtD_rmTyFS4Sdh:-NgwNpw41nq3RV6YOK3w:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/6783bad98ff5fc483c06596bc3fec029481d9762/multibody/mpm/test/particles_test.cc#L82)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

2. You could have just compared the data from `particles` and that from `reordered_particles` based on `ordering`. But this is fine too, just more brittle.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-17 07:38 UTC, zeshunzong reviewed
> Reviewed 4 of 7 files at r4, 5 of 7 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)



<!-- Sent from Reviewable.io -->

2023-10-17 07:39 UTC, merged