Add stvk hencky vonMises model
zeshunzong/drake pull request #12
Opened 2023-10-10 18:29 UTC by zeshunzong

2023-10-10 18:33 UTC, zeshunzong reviewed
+@xuchenhan-tri 

I am aware that many quantities are repeatedly computed (e.g. svd or so). But I suppose they can be addressed if we do some caching. Right now the math seems good to me and it is readable.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12#-:-NgPqfoVECkFy_JDRXRl:bl8brgv)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgPr89vB5DsEGfR3n1j:-NgPr89vB5DsEGfR3n1k:biqbrxc) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L90)):*
> ```cpp
>       // clang-format off
>       (*dPdF)(ij, rs) = (*dPdF)(rs, ij) =
>            psi_derivatives.psi_00 * ssd.U(i, 0) * ssd.V(j, 0) * ssd.U(r, 0) * ssd.V(s, 0) // 0000
> ```

Compiler gives me warning as the line is too long, but I think the current version is super clear on what is being computed.


<!-- Sent from Reviewable.io -->

2023-10-10 22:03 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgPr89vB5DsEGfR3n1j:-NgQbNv31ul8Pd0D5YnA:b-guk70f) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L90)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Compiler gives me warning as the line is too long, but I think the current version is super clear on what is being computed.
</blockquote></details>

You can use `// clang-format off` to opt out clang format and then use `// clang-format on` to turn it back on


<!-- Sent from Reviewable.io -->

2023-10-11 01:10 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgPr89vB5DsEGfR3n1j:-NgRGyjWCJocYjx4sors:b-y5tmil) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You can use `// clang-format off` to opt out clang format and then use `// clang-format on` to turn it back on
</blockquote></details>

` psi_derivatives.psi_00 * ssd.U(i, 0) * ssd.V(j, 0) * ssd.U(r, 0) * ssd.V(s, 0) // NOLINT 0000` should be able to suppress linter.


<!-- Sent from Reviewable.io -->

2023-10-11 22:59 UTC, xuchenhan-tri requested changes
I made a pass. PTAL.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12#-:-NgVxj-X2vusTcrd8iQ0:b-ok6jv6)* status: 1 of 5 files reviewed, 22 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 39 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgV_MZ93fdyaB2WEauP:-NgV_MZA5v38pngyy2lc:b-ctevwv) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L39)):*
> ```objc
> // Given the SVD of elastic deformation gradient Fᴱ = U Σ Vᵀ,
> // the Hencky strain             ε = 1/2ln(Fᴱ Fᴱ^T) = U ln(Σ) Uᵀ
> // the energy density            ψ = U Σ⁻¹(μln(Σ)²+1/2*λtr(ln(Σ))²I) Vᵀ
> ```

nit, why is energy density here not a scalar?



_Code quote:_
```objc
ψ = U Σ⁻¹(μln(Σ)²+1/2*λtr(ln(Σ))²I) Vᵀ
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 42 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVgwci8llsR10TyqrF:-NgVgwci8llsR10TyqrG:b-7ilvfu) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L42)):*
> ```objc
> // the (trial) Kirchhoff stress  τ = U (2μln(Σ)+λtr(ln(Σ))I) Uᵀ
> // the deviatoric component of trial stress is
> //                  dev(τ) = τ - 1/3*tr(τ)I = U (2μln(Σ)+2/3*μ tr(ln(Σ))I) Uᵀ
> ```

typo?



_Suggestion:_
```objc
dev(τ) = τ - 1/3*tr(τ)I = U (2μln(Σ)-2/3*μ tr(ln(Σ))I) Uᵀ
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 43 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVswAn-l3kB7m3igB8:-NgVswAn-l3kB7m3igB9:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L43)):*
> ```objc
> // the deviatoric component of trial stress is
> //                  dev(τ) = τ - 1/3*tr(τ)I = U (2μln(Σ)+2/3*μ tr(ln(Σ))I) Uᵀ
> // The we can rewrite the associate flow rule with (BW 7.53)
> ```

typo



_Suggestion:_
```objc
Then
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 52 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhXdpBcwXnA0yZxDg:-NgVhXdpBcwXnA0yZxDh:b-cr8py0) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L52)):*
> ```objc
> // are in the same direction, i.e.
> //      dev(τⁿ⁺¹) = k dev(τ)
> //                 k: f(τⁿ⁺¹) = 0 on the yield surface
> ```

nit readability



_Suggestion:_
```objc
for k such that f(τⁿ⁺¹) = 0 on the yield surface
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 53 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhhtz1IPWNylxCJUe:-NgVhhu-3sGwiBwKs_dF:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L53)):*
> ```objc
> //      dev(τⁿ⁺¹) = k dev(τ)
> //                 k: f(τⁿ⁺¹) = 0 on the yield surface
> // Solving for k gives us the prjected states. The above derivation leads to the
> ```

typo



_Suggestion:_
```objc
projected
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 60 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVajvEDADEndaw4yW1:-NgVajvEDADEndaw4yW2:b-ry44wy) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L60)):*
> ```objc
> template <typename T>
> class StvkHenckyWithVonMisesModel : public ElastoPlasticModel<T> {
>  public:
> ```

nit, copy/move/assign? I assume you want to forbid those since you already have `Clone()`?
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 61 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhvZw4TQHIQAqxYTD:-NgVhvZw4TQHIQAqxYTE:bpdn5j8) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L61)):*
> ```objc
> class StvkHenckyWithVonMisesModel : public ElastoPlasticModel<T> {
>  public:
>   // Constructs the model with an additional parameter yield_stress.
> ```

nti document unit of `yield_stress`.
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 71 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVxWZy0HcPG_B4qGJm:-NgVxWZy0HcPG_B4qGJn:bgnmnmw) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L71)):*
> ```objc
>   }
> 
>   T CalcStrainEnergyDensity(const Matrix3<T>& FE) const final;
> ```

There should be a note here emphasizing that the energy density (and the stress and the stress derivatives computed below) are ignoring the effect of plasticity.
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 103 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVb41CESlQeJp1gfWj:-NgVb41CESlQeJp1gfWk:b-pc90ol) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L103)):*
> ```objc
>   };
> 
>   StrainStressData ComputeStrainStressData(const Matrix3<T>& F_trial) const;
> ```

nit, consider making the parameter name more generic since, IIUC, you also want to invoke this function with FE.



_Suggestion:_
```objc
 StrainStressData ComputeStrainStressData(const Matrix3<T>& F) const;
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 128 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVbHuS8gZCRtQdrM_o:-NgVbHuS8gZCRtQdrM_p:b-8gb8ew) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L128)):*
> ```objc
>     T p12;  // (psi_1+psi_2)/(sigma1+sigma2), need to clamp denominator
> 
>     Vector3<T> dpsi_dsigma_i;
> ```

nit, not sure what this is.
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 131 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVaDCeCS4venkUIq2f:-NgVaDCeCS4venkUIq2g:b-v1ufw4) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L131)):*
> ```objc
>   };
> 
>   // Returns the (i,j)'s entry of Matrix B01. See accompanied doc.
> ```

nit, unclear to me what B01 is



_Code quote:_
```objc
// Returns the (i,j)'s entry of Matrix B01. See accompanied doc.
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 170 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgViEP46Eti8ijutcko:-NgViEP46Eti8ijutckp:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L170)):*
> ```objc
>                           Matrix3<T>* F_trial) const;
> 
>   T yield_stress_;
> ```

nit



_Suggestion:_
```objc
T yield_stress_{};
```
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 19 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgViWPzD3eSvLyooyhH:-NgViWQ-B4eMpwFNwuky:b-48mzx6) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L19)):*
> ```cpp
> T StvkHenckyWithVonMisesModel<T>::CalcStrainEnergyDensity(
>     const Matrix3<T>& FE) const {
>   // psi = mu tr((log S)^2) + 1/2 lambda (tr(log S))^2
> ```

n [...]

2023-10-11 22:59 UTC, xuchenhan-tri reviewed
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: all files reviewed, 22 unresolved discussions (waiting on @zeshunzong)



<!-- Sent from Reviewable.io -->

2023-10-12 07:49 UTC, zeshunzong reviewed
I forgot to squash commits when merging poisson disk. When I tried to revert that, some existing files pop up here...

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12#-:-NgXqZpg9yem7nx66CDD:b-cuyw0n)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 39 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgV_MZ93fdyaB2WEauP:-NgXAzmv10J3XaMjfKLm:bn0cmy4) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L39)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, why is energy density here not a scalar?
</blockquote></details>

done refer to doc
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 42 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVgwci8llsR10TyqrF:-NgXB8c64YUwxVPnrqoB:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L42)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo?
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 43 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVswAn-l3kB7m3igB8:-NgXBZjABn4GVGpy6ww9:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L43)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 52 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhXdpBcwXnA0yZxDg:-NgXBpMtDQUVdIgFUAEw:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit readability
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 53 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhhtz1IPWNylxCJUe:-NgXBpz4D7uv4iwT4k6x:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 60 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVajvEDADEndaw4yW1:-NgXBrcbCArVcgmDsIFT:b-iggz4w) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L60)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, copy/move/assign? I assume you want to forbid those since you already have `Clone()`?
</blockquote></details>

let's have a discussion on this
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 61 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVhvZw4TQHIQAqxYTD:-NgXD-do5EVstlwtmEo6:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L61)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nti document unit of `yield_stress`.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 71 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVxWZy0HcPG_B4qGJm:-NgXEBt_0lflZRPMP6ku:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L71)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There should be a note here emphasizing that the energy density (and the stress and the stress derivatives computed below) are ignoring the effect of plasticity.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 103 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVb41CESlQeJp1gfWj:-NgXF5CE04We5pc4JBzE:b3ul62i) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L103)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, consider making the parameter name more generic since, IIUC, you also want to invoke this function with FE.
</blockquote></details>

I remembered that you once mentioned that we should not use "F" as for other users of Drake F has other meanings -- I forgot exactly what that is. I was hoping for another term for F but could not think of one, so just stuck with F_trial. Open to suggestion.
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 128 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVbHuS8gZCRtQdrM_o:-NgXDCFBCyTttf1SB7oa:b-flpiww) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, not sure what this is.
</blockquote></details>

done deleted
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 131 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVaDCeCS4venkUIq2f:-NgXFXLuEyTm1uubSALA:b-4h6pbi) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L131)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, unclear to me what B01 is
</blockquote></details>

I thought this should be sufficiently clear with the doc. add a bit more comments, take a look!
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 170 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgViEP46Eti8ijutcko:-NgXEzaN2kBX67_X__Nx:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L170)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 19 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgViWPzD3eSvLyooyhH:-NgXKS5Y31u3OdPYrN4x:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit notation consistency
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVjVjR88ISfabgAiNj:-NgWoQzv5bZLtFqQmqVz:b-t57o2c) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, not not compute this from PK1 (or vice versa)?
</blockquote></details>

I do not plan to actually call this function in [...]

2023-10-13 07:18 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 60 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVajvEDADEndaw4yW1:-Ngbst2sEMCTvS5x5oia:b-lkeaf9) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L60)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

let's have a discussion on this
</blockquote></details>

also enabled default copy etc
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgPr89vB5DsEGfR3n1j:-NgboSbi0iIfNBeDbFQw:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

` psi_derivatives.psi_00 * ssd.U(i, 0) * ssd.V(j, 0) * ssd.U(r, 0) * ssd.V(s, 0) // NOLINT 0000` should be able to suppress linter.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 145 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVlWeQ6T-QqyBUeGOk:-NgbpIJ9DBulKG_qN2ru:besf1zo) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L145)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should check that sigma > 0 here.
</blockquote></details>

add drake_assert here
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc` line 158 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVkn1p-pvK7dP4ClS9:-NgbsYPHC4Bms2mS6WYq:b-u81394) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.cc#L158)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW I believe you can use designated initializer here to avoid some copies without losing readability.

Even if you decide to keep the copies, it's probably still a good idea to use designated initializer to prevent messing up the order of the data member.
</blockquote></details>

balancing between two
___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 46 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVwKAk3_xPMKo87TGu:-NgbirfU5ucE7mfwiW4K:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L46)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

let's discuss this.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-16 22:11 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with some parting thoughts.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12#-:-NguXjtY35jZYBvcC_pp:b-i198vy)* status: all files reviewed, 4 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 103 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVb41CESlQeJp1gfWj:-NguVU9TBh7wOyJaCUhO:bhwkxxq) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L103)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

I remembered that you once mentioned that we should not use "F" as for other users of Drake F has other meanings -- I forgot exactly what that is. I was hoping for another term for F but could not think of one, so just stuck with F_trial. Open to suggestion.
</blockquote></details>

what about just `DeformationGradient`? This signature would make future me pause when calling `model.ComputeStrainStressData(FE)`.
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 105 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguVM8S3vuV6bCm4zMF:-NguVM8S3vuV6bCm4zMG:bm1yy19) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L105)):*
> ```objc
>   friend class StvkHenckyWithVonMisesModelTester;
> 
>   // Given deformation gradient F, stores the following results
> ```

nit. the doc should be moved along with the struct.
___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 24 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguWVU32S41u4xyV3W2:-NguWVU32S41u4xyV3W3:bnbk2nv) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L24)):*
> ```cpp
> class StvkHenckyWithVonMisesModelTester {
>  public:
>   void TestReturnMap() {
> ```

minor, the testing strategy here could use some clarification. IIUC, you have picked F E, nu, and yield_stress specifically so that the deformation is in the plastic region. Then after applying the return mapping, you are checking that the projected stress is indeed on the yield surface.

If that's the right idea, you should capture and document it.
___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 116 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguX75mDeC96OKXlofo:-NguX75mDeC96OKXlofp:b-f1a6rl) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L116)):*
> ```cpp
> GTEST_TEST(StvkWithVonMisesModelTest, TestReturnMapping) {
>   StvkHenckyWithVonMisesModelTester tester;
>   tester.TestReturnMap();
> ```

BTW, if you value consistency (and you should), you can put the meat of the test here (like you did below) and leave only what's necessary for the tester (i.e. things that are private to the dut class). 

Also, do you really need the tester? What's the private data/function you are using?


<!-- Sent from Reviewable.io -->

2023-10-17 08:58 UTC, zeshunzong reviewed
> Reviewed 4 of 13 files at r3, 5 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: 3 of 13 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 103 at r1](https://reviewable.io/reviews/zeshunzong/drake/12#-NgVb41CESlQeJp1gfWj:-NgwgZRXEU5SP3kXZ7WD:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5a9c3ac2ebd319005bcd250830cfadadece25979/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L103)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

what about just `DeformationGradient`? This signature would make future me pause when calling `model.ComputeStrainStressData(FE)`.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h` line 105 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguVM8S3vuV6bCm4zMF:-NgwgYAO0oB2U88GscYW:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/stvk_hencky_with_von_mises_model.h#L105)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit. the doc should be moved along with the struct.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 24 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguWVU32S41u4xyV3W2:-NgwjV2a4Nv9-_KINSiA:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, the testing strategy here could use some clarification. IIUC, you have picked F E, nu, and yield_stress specifically so that the deformation is in the plastic region. Then after applying the return mapping, you are checking that the projected stress is indeed on the yield surface.

If that's the right idea, you should capture and document it.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 116 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguX75mDeC96OKXlofo:-NgwjXcb0wZ-VygjxdpL:bn34akg) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L116)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, if you value consistency (and you should), you can put the meat of the test here (like you did below) and leave only what's necessary for the tester (i.e. things that are private to the dut class). 

Also, do you really need the tester? What's the private data/function you are using?
</blockquote></details>

done tester removed. Originally ComputeYieldFunction() and ComputeStrainStressData() are private. I am OK with first one being public. For the second one, before I insisted that it should be private. But not since the struct type it returns is open to public, and this is the only way to compute that struct, I guess it also makes sense to make that function public as well. Besides, I hate friend functions all the time and removing them is indeed refreshing.


<!-- Sent from Reviewable.io -->

2023-10-17 18:26 UTC, xuchenhan-tri approved these changes
> Reviewed 10 of 13 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc` line 116 at r2](https://reviewable.io/reviews/zeshunzong/drake/12#-NguX75mDeC96OKXlofo:-Ngyspp72zL2qXoyTDJo:bpuc2k4) ([raw file](https://github.com/zeshunzong/drake/blob/4c9e62f6b77eb1758c7df94ebd1fa2212231ae0f/multibody/mpm/constitutive_model/test/stvk_hencky_with_von_mises_model_test.cc#L116)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done tester removed. Originally ComputeYieldFunction() and ComputeStrainStressData() are private. I am OK with first one being public. For the second one, before I insisted that it should be private. But not since the struct type it returns is open to public, and this is the only way to compute that struct, I guess it also makes sense to make that function public as well. Besides, I hate friend functions all the time and removing them is indeed refreshing.
</blockquote></details>

FYI, https://drake.mit.edu/styleguide/cppguide.html#Friends

Friendship serves its purpose in certain places, just not here.


<!-- Sent from Reviewable.io -->

2023-10-17 18:28 UTC, merged