finish p2g
zeshunzong/drake pull request #19
Opened 2023-10-26 06:53 UTC by zeshunzong

2023-10-26 06:55 UTC, zeshunzong reviewed
@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/19#-:-Nhel1HD8DWfq0Il_c0f:bi9qar7)* status: 0 of 18 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-26 17:20 UTC, zeshunzong reviewed
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/19#-:-Nhh-BA3A-y43CxupuVi:bk7giky)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2023-10-30 18:59 UTC, xuchenhan-tri requested changes
I reviewed all non-test files. This looks considerably cleaner. PTAL at my comments.

> Reviewed 16 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/19#-:-Ni0x-DUApH0ohaiBy2y:b-i8pix4)* status: 16 of 18 files reviewed, 28 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 22 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh2W_GE7V2zb29G3ao:-Nhh2W_GE7V2zb29G3ap:b-ww7ogh) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L22)):*
> ```objc
>  */
> template <typename T>
> struct GridData {
> ```

nit, `GridData` has a bunch of invariants and should be a class instead of a struct.

https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Classes
___
*[`multibody/mpm/grid_data.h` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh3Jf8Dbppix7X7Cjq:-Nhh3Jf8Dbppix7X7Cjr:b-d5on8) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L41)):*
> ```objc
>     velocities.resize(num_active_nodes);
>     forces.resize(num_active_nodes);
>     std::fill(masses.begin(), masses.begin() + num_active_nodes, 0.0);
> ```

BTW you can do



_Suggestion:_
```objc
 std::fill(masses.begin(), masses.end(), 0.0);
```
___
*[`multibody/mpm/grid_data.h` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh3ZFCBps-5QMGFsHq:-Nhh3ZFCBps-5QMGFsHr:bb2i47u) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L57)):*
> ```objc
>       velocities[i] = velocities[i] / masses[i];
>     }
>   }
> ```

This is a brittle. Inadvertently calling this function twice is immediately a bug. You could probably achieve the same effect (i.e. storing both velocity and momentum) in a single piece of memory with std::variant.
___
*[`multibody/mpm/grid_data.h` line 63 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh5cOyExwHV66i9lhk:-Nhh5cOyExwHV66i9lhl:b-soqva4) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L63)):*
> ```objc
>    */
>   internal::MassAndMomentum<T> ComputeTotalMassAndMomentumGrid(
>       const SparseGrid<T>& grid) const {
> ```

There is compatibility requirement between `this` data and the given `grid`. That should be documented.
___
*[`multibody/mpm/mpm_transfer.h` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0nGWwAqc1wSPQBY_I:-Ni0nGWwAqc1wSPQBY_J:bsrg5kr) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.h#L24)):*
> ```objc
> class MpmTransfer {
>  public:
>   // DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(PadSplatter);
> ```

BTW, do you need copy move assign? You can probably put the MpmTransfer in the model (instead of context) so it doesn't need value semantic.
___
*[`multibody/mpm/mpm_transfer.h` line 33 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0nmGnAKmzw4jj2WPp:-Ni0nmGnAKmzw4jj2WPq:b-b7v5mj) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.h#L33)):*
> ```objc
>    *
>    */
>   void SetUpTransfer(SparseGrid<T>* grid, Particles<T>* particles) const;
> ```

BTW, since this class has no data member at all. You can make all the member functions static.
___
*[`multibody/mpm/mpm_transfer.cc` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0pW-s04jpoGVRRlSJ:-Ni0pW-s04jpoGVRRlSK:b-22uv1b) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L11)):*
> ```cpp
>                                    Particles<T>* particles) const {
>   if (grid->num_active_nodes() == 0) {
>     // TODO(yiminlin.tri): Magic number
> ```

Is this todo still relevant?
___
*[`multibody/mpm/mpm_transfer.cc` line 30 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0r8vl53yd5S8EEj0f:-Ni0r8vl53yd5S8EEj0g:b-7q4dzr) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L30)):*
> ```cpp
>                          GridData<T>* grid_data) const {
>   size_t p_start, p_end;
>   std::vector<Pad<T>> local_pads(grid.num_active_nodes());
> ```

Ouch, that's a lot of heap allocation. We should avoid it.
___
*[`multibody/mpm/mpm_transfer.cc` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0rWvrBHpykILT3ywA:-Ni0rWvrBHpykILT3ywB:b-e0xh8o) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L41)):*
> ```cpp
>   }
>   for (size_t i = 0; i < grid.num_active_nodes(); ++i) {
>     if (grid.GetBatchSizeAtNode(i) != 0) {
> ```

Is this predicate ever false? IIUC, this is false only if the transfer is not properly set up, right?
___
*[`multibody/mpm/mpm_transfer.cc` line 63 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0sHMO1R_FzMhc1ds_:-Ni0sHMO1R_FzMhc1dsa:bbb16td) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L63)):*
> ```cpp
>         node_index_local = (c + 1) + 3 * (b + 1) + 9 * (a + 1);
> 
>         grid_data->masses[grid.Reduce3DIndex(node_index_3d)] +=
> ```

nit, you could probably compute this once and reuse instead of relying on the compiler to figure this out.



_Code quote:_
```cpp
grid.Reduce3DIndex(node_index_3d)
```
___
*[`multibody/mpm/pad.h` line 18 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh5x714UYF-yIlXpHX:-Nhh5x714UYF-yIlXpHY:bayb10m) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad.h#L18)):*
> ```objc
> template <typename T>
> struct Pad {
>   std::array<T, 27> pad_masses;
> ```

BTW probably worth mentioning how the 27 numbers are ordered.
___
*[`multibody/mpm/pad_splatter.h` line 20 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhFFTw0WQYN6Zu1Mtl:-NhhFFTw0WQYN6Zu1Mtm:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L20)):*
> ```objc
>  * transferring particle data to neighbor grid nodes. Here we only support a
>  * quadratic b-spline interpolation.
>  * Each particle p has its own PadSplatter. The attrbutes stored in this class
> ```

typo



_Suggestion:_
```objc
attributes
```
___
*[`multibody/mpm/pad_splatter.h` line 30 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhIKiz9U7TOoFXsVHe:-NhhIKiz9U7TOoFXsVHf:bxkq6nf) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L30)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(PadSplatter);
> 
>   PadSplatter() {}
> ```

I think you can roll grid dx and particle batch index into this class. That, along with making SparseGrid::GetPositionAt() a free function, allows you to decouple this class from the SparseGrid class.

With that this class's public API should be cleaner with just

`PadSplatter::Update(const Vector3<T>& particle_position);`

and 

`PadSplatter::Splat(const Data&... data..., Pad* pad) const;`
___
*[`multibody/mpm/pad_splatter.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhFQ9v0D9BcSBOnIJn:-NhhFQ9v0D9BcSBOnIJo:bfqrefl) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L38)):*
> ```objc
>    * is to call the Update() function.
>    */
>   void SetOutdated() { is_up_to_date_ = false; }
> ```

Is this used?
___
*[`multibody/mpm/pad_splatter.h` line 72 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhKLw4BNQETEaVoE4r:-NhhKLw4BNQETEaVoE4s:b-egymhc) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/mul [...]

2023-11-01 23:43 UTC, zeshunzong reviewed
I haven't addressed all the details.

I added an unfinished G2P, primarily helps me to see how and where particles are changed. 

Here is the essential part.

Since the chain of info inevitably involves both grid and particles, i think at least a flag is needed, ( I would prefer not to cache everything here). I was hesitating between having two flags (one for grid, one for particles) or only one. I thought about the whole pipeline and it seems that outside the standard p2g and g2p, we never use grid alone. Grid is always used in tandem with particles, or particles is used alone. So I decided to keep only one flag in particles

There is a boolean Particles.grid_and_particles_and_splatters_need_update_. This flag is marked as true as long as particle position changes -- initially adding particles, and advecting particles x += dt * v. Throughout the class there is NO other way to modify particle positions. This ensures that the flag will always be triggered.

The boolean is checked whenever an operation that involves particles (and may or may not grid) is performed, including p2g and g2p. Other operations I can think of right now are forming grid force hessian, and contact jacobian. All of them will involve at least particles. 

The boolean is reset in MpmTransfer.SetupTransfer() -- I was hesitating whether we should combine line 18 and line 21 in mpm_transfer.cc, as in 85-90 in particles.h (the idea is the same, deeply bind the three operations together). This is the only place that the boolean can be reset.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/19#-:-NiCC7ew5_1lVBuuOvNr:b-inp1wd)* status: 7 of 18 files reviewed, 15 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/grid_data.h` line 22 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh2W_GE7V2zb29G3ao:-NiCBFTZArr-Lr2WudlE:br8bylw) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, `GridData` has a bunch of invariants and should be a class instead of a struct.

https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Classes
</blockquote></details>

partially fixed, more to be done
___
*[`multibody/mpm/grid_data.h` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Nhh3Jf8Dbppix7X7Cjq:-Ni5Yx1B3-zuuYKzS4ga:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/grid_data.h#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW you can do
</blockquote></details>

done
___
*[`multibody/mpm/mpm_transfer.h` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0nGWwAqc1wSPQBY_I:-Ni7MSD_CNRDp7TUoN4E:bq2fvpr) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.h#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, do you need copy move assign? You can probably put the MpmTransfer in the model (instead of context) so it doesn't need value semantic.
</blockquote></details>

make it default now
___
*[`multibody/mpm/mpm_transfer.h` line 33 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0nmGnAKmzw4jj2WPp:-Ni7W8gt3HHGAegHG12N:b-416sof) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, since this class has no data member at all. You can make all the member functions static.
</blockquote></details>

obsolete comment. done
___
*[`multibody/mpm/mpm_transfer.cc` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0pW-s04jpoGVRRlSJ:-Ni5ZA6V1m0OkBsZY9rd:bqnpoas) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is this todo still relevant?
</blockquote></details>

done per discussion
___
*[`multibody/mpm/mpm_transfer.cc` line 30 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0r8vl53yd5S8EEj0f:-NiCBbJ111-Y9Q0QIt5S:bkkay6e) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ouch, that's a lot of heap allocation. We should avoid it.
</blockquote></details>

attribute in Mpm transfer now, also reserved, in SetupTransfer()
___
*[`multibody/mpm/mpm_transfer.cc` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0rWvrBHpykILT3ywA:-Ni7PF-V9QigXcAZAhL6:b48rgn1) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is this predicate ever false? IIUC, this is false only if the transfer is not properly set up, right?
</blockquote></details>

done explained
___
*[`multibody/mpm/pad_splatter.h` line 20 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhFFTw0WQYN6Zu1Mtl:-Ni5ZMsF2vDWmHcL5mQF:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`multibody/mpm/pad_splatter.h` line 38 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhFQ9v0D9BcSBOnIJn:-NiCBrP-ApcdIpdYFsBj:b-melyys) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L38)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

a new boolean is used, see general comments 
___
*[`multibody/mpm/pad_splatter.h` line 72 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhKLw4BNQETEaVoE4r:-Ni5ZslKAX2J6fBU7ZKk:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L72)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, structural binding helps with readability here.
</blockquote></details>

done
___
*[`multibody/mpm/pad_splatter.h` line 95 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-NhhL6eHCn28Kx2YL6hM:-Ni5ja4f8yabJAcLHd0O:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/pad_splatter.h#L95)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the doc should emphasize that the pads are accumulated to, not overwritten.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 271 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0qibLB3XuKfknuuDQ:-NiCBzdQ17lWBmPRTVIm:b-s9ucm5) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/particles.h#L271)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Moving this function to the private section and update the pad splatters automatically whenever a particle's position changes would make this class less brittle.
</blockquote></details>

see general comments section
___
*[`multibody/mpm/sparse_grid.h` line 135 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0uVeBE9MLGlJ_DPlv:-Ni5joDmA93FvdBh4YWe:b-n6rhrt) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/sparse_grid.h#L135)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit I don't understand what this sentence is trying to say.
</ [...]

2023-11-02 23:44 UTC, xuchenhan-tri requested changes
I'm not sure if I follow exactly everything you said here. I understand the fact that change in particle positions invalidates the ordering of particles and grid sparsity pattern. The correct solution would be to use Drake's caching system. For now, I'm fine with manually handling that with MpmTransfer. But still, I feel like your class interfaces can be cleaned up more.

Here is how I think the classes should look like in broad stroke pseudocode. Hope it helps pin the discussion:

```cpp
template <typename T>
class Particles {
 public:
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Particles);

  /* Sort the particles into batches based on their positions.
   Computes base_nodes_, batch_starts_, batch_sizes_.
   Resets weights_.
   Sorts the particle attributes based on base nodes. */
  void SortIntoBatches(double dx) {}

  /* Resizes the given `pads` and writes the particle data into the pads.
   @warn This function assumes that the particles are already sorted. When in
   doubt, call Sort() before invoking this function. */
  void SplatToPads(std::vector<Pad<T>>* pads) const {
    pads->resize(num_batches());
    for (int i = 0; i < num_batches(); ++i) {
      Pad<T>& pad = (*pads)[i];
      pad.set_base_node(base_nodes_[i]);
      const int p_start = batch_starts_[i];
      const int p_end = p_start + batch_sizes_[i];
      for (int p = p_start; p < p_end; ++p) {
        weights_[p].SplatParticleDataToPad(*this, p, &pad);
      }
    }
  }

  int num_particles() const { return positions_.size(); }

  int num_batches() const { return base_nodes_.size(); }

 private:
  // Per batch data.
  // base_nodes_[i] is the 3d index of the base node of the i-th batch.
  std::vector<Vector3<int>> base_nodes_;
  // batch_starts_[i] is the index of the first particle in the i-th batch.
  std::vector<int> batch_starts_;
  // batch_sizes_[i] is the number of particles in the i-th batch.
  std::vector<int> batch_sizes_;

  // Per particle data.
  std::vector<InterpolationWeights<T>> weights_;
  // Physical data carried by particles
  std::vector<Vector3<T>> positions_{};
  std::vector<Vector3<T>> velocities_{};
  std::vector<T> masses_{};
};

template <typename T>
class InterpolationWeights {
 public:
  void Reset(const Vector3<int>& base_node, const Vector3<T>& position,
             double dx) {
    // Sets weights_ and weight_graidents_;
  }

  void SplatParticleDataToPad(const Particles<T>& particles, int p,
                              Pad<T>* pad) {
    // Get p-th particle's data from `particles` and write it to pad with the
    // weights_ and wieght_gradients_. */
  }

 private:
  std::array<T, 27> weights_{};
  std::array<Vector3<T>, 27> weight_gradients_{};
};

template <typename T>
class SparseGrid {
 public:
  void MarkActiveGridNodes(const std::vector<Vector3<int>>& base_nodes) {
    // Mark the one ring of `base_nodes` as active.
    // Build 1d_to_3d_ and 3d_to_1d_;
  }

  // @pre Pads doesn't contain data into non-active region of the grid.
  void GatherFomPads(const std::vector<Pad<T>>& pads,
                     GridData<T>* grid_data) const {
    grid_data->Resize(1d_to_3d_.size());
    for (const Pad<T>& pad : pads) {
      const Vector3<int>& base_node = pad.base_node();
      // Add pad data to grid data.
      for (int a = -1, 0, 1) {
        for (int b = -1, 0, 1) {
          for (int c = -1, 0, 1) {
            int index = 3d_to_1d_.at(Vector3<int>(a, b, c) + base_node);
            (*grid_data)[i] += pad.at(a, b, c);
          }
        }
      }
    }
  }

 private:
  std::vector<Vector3<int>> 1d_to_3d_;
  std::unordered_map<Vector3<int>, int> 3d_to_1d_;
};

template <typename T>
struct Pad {
  std::array<T, 27> mass;
  std::array<T, 27> velocity;
  Vector3<int> base_node;
};

template <typename T>
class MpmTransfer {
  static void Initialize(Particles<T>* p, SparseGrid<T>* g) {
    p->SortIntoBatches(g->dx());
    g->MarkActiveGridNodes(p->get_base_nodes());
  }

  void P2G(const Particles<T>& p, const SparseGrid<T>& grid,
           GridData<T>* data) {
    p.SplatParticleDataToPad(&pads_);
    g.GatherFomPads(pads_, data);
  }

 private:
  std::vector<Pad<T>> pads_;
};
```

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/19#-:-NiHOFeO-JOwAiQymWSy:bew4isj)* status: 7 of 18 files reviewed, 15 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/mpm_transfer.cc` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/19#-Ni0pW-s04jpoGVRRlSJ:-NiH2IMFAfe4VVI52hNb:b-z44d8b) ([raw file](https://github.com/zeshunzong/drake/blob/bf40b1ae431cd3acc7668afc5b694f8a407ccd53/multibody/mpm/mpm_transfer.cc#L11)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done per discussion
</blockquote></details>

The comment should explain why we are reserving the requested amount of memory.

"This is indeed an upper bound" is vague. What is the an upper bound of what?


<!-- Sent from Reviewable.io -->

2023-11-02 23:49 UTC, zeshunzong commented
okay I do agree this is cleaner. I was somehow stuck in Yimin's ordering of those operations.





<!-- Sent from Reviewable.io -->

2023-12-08 01:24 UTC, closed without merging