Add mpm model and test
zeshunzong/drake pull request #28
Opened 2024-01-02 18:12 UTC by zeshunzong

2024-01-02 18:12 UTC, zeshunzong reviewed
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28#-:-NnAN6Z_9ms4gfuzzpTe:bk7giky)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2024-01-02 22:03 UTC, xuchenhan-tri requested changes
I made a pass through the non-testing code. PTAL and see what you think.

> Reviewed 11 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28#-:-NnBBoup5RuqlnEriVjP:bmrcwjw)* status: 11 of 14 files reviewed, 22 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 86 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAc43U-69lsbCTQXA4:-NnAc43U-69lsbCTQXA5:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/grid_data.h#L86)):*
> ```objc
>    * @pre index_1d < num_active_nodes()
>    */
>   T GetMassAt(size_t index_1d) const {
> ```

nit



_Suggestion:_
```objc
  const T& GetMassAt(size_t index_1d) const {
```
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAe87v8FYEfCGM47er:-NnAe87v8FYEfCGM47es:buvsivm) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
> ```objc
>                                    const Vector3<int>& base_node,
>                                    P2gPad<T>* p2g_pad) const {
>     (*p2g_pad).base_node = base_node;
> ```

BTW, the implementations should be in .cc files.
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAeJ7OBE8ExVtMKVmn:-NnAeJ7OBE8ExVtMKVmo:b2mny9p) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
> ```objc
>                                    const Vector3<int>& base_node,
>                                    P2gPad<T>* p2g_pad) const {
>     (*p2g_pad).base_node = base_node;
> ```

btw, a more common spelling would be: 



_Suggestion:_
```objc
p2g_pad->base_node = base_node;
```
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAeTVMBilkU1NWkS6w:-NnAeTVMBilkU1NWkS6x:b-7ikxmd) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
> ```objc
>                                    const Vector3<int>& base_node,
>                                    P2gPad<T>* p2g_pad) const {
>     (*p2g_pad).base_node = base_node;
> ```

This really should be a DRAKE_DEMAND/ASSERT instead of an assignment. `Reset()` is in charge of setting the base nodes, and any other member function should not modify it.



_Code quote:_
```objc
 (*p2g_pad).base_node = base_node;
```
___
*[`multibody/mpm/interpolation_weights.h` line 154 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAf4UV-FJAZaPh5u4i:-NnAf4UV-FJAZaPh5u4j:b-20paoe) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L154)):*
> ```objc
>           // loop over 27 neighbor nodes
>           // node_index_local is from 0 to 26
>           node_index_local = (c + 1) + 3 * (b + 1) + 9 * (a + 1);  // 0-26
> ```

BTW, is this just the same as initializing `node_index_local` to 0 and post increment? It may be more intuitive to some readers if written that way. Your call.



_Code quote:_
```objc
node_index_local = (c + 1) + 3 * (b + 1) + 9 * (a + 1);  // 0-26
```
___
*[`multibody/mpm/mpm_model.h` line 14 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB0aQP-oHHP6wk5Xy3:-NnB0aQQ2ejO-FSBoENX:b-npznzo) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L14)):*
> ```objc
> 
> template <typename T>
> class MpmModel {
> ```

This class needs some documentation. What would help me is some examples on how this class interacts with other classes. Just by looking at the set of APIs, this doesn't feel like a "model" but instead feels more like a mix between a "solver" and a "model". And I'm not sure what this class is trying to achieve in addition to what the `MpmTransfer` class is already capable of.
___
*[`multibody/mpm/mpm_model.h` line 31 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB3Jn-556WJrUna7wb:-NnB3Jn-556WJrUna7wc:b-gy6lkw) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L31)):*
> ```objc
>                                  const Particles<T>& particles, double dt) {
>     ParticlesData<T> particles_data{};  // TODO(zeshunzong): attribute?
>     transfer_.G2P(sparse_grid, grid_data, particles, &particles_data);
> ```

BTW, IIUC, this is writing particle data like the B matrix that we are just going to throw away. If that's a case, at least put a TODO here so we can come back and eliminate this inefficiency.
___
*[`multibody/mpm/mpm_model.h` line 59 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAfXyU4rTuWWUvsLMv:-NnAfXyU4rTuWWUvsLMw:b-c67whg) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L59)):*
> ```objc
> 
>  private:
>   Vector3<T> gravity_{0.0, 0.0, -9.8};
> ```

Ultimately, gravity needs to be configurable. It's fine to hardcode for now if you want to focus on that later. Use -9.81 for the hardcode value.
___
*[`multibody/mpm/mpm_model.h` line 62 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnBAVjZ4VFCKV2sn2vm:-NnBAVj_4iUAwIoYdWP0:b-wh6b3g) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L62)):*
> ```objc
>   MpmTransfer<T> transfer_;
> 
>   DeformationScratch<T> scratch_{};
> ```

I'm finding it increasingly hard to reason through the mutable scratch data members you leave among different classes and the non-const member functions all over the place. It's hard to tell what are states, what are state-dependent data, and what are just temporary scratches. I wonder if there's a way to make those distinction clear.



_Code quote:_
```objc
DeformationScratch<T> scratch_{};
```
___
*[`multibody/mpm/mpm_transfer.h` line 70 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB8sF_5iddltNmDD8j:-NnB8sF_5iddltNmDD8k:b-qtcflq) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_transfer.h#L70)):*
> ```objc
>  * particles.AdvectParticles(dt);
>  * Output Gₙ₊₁:=Gₙ, Pₙ₊₁:=Pₙ.
>  * ```
> ```

An updated pseudocode here might help me better understand the role of MpmModel and how it fits in the explicit/implicit scheme.



_Code quote:_
```objc
 * Explicit temporal advancement:
 * ```
 * mpm_transfer.SetupTransfer(&sparse_grid, &particles);
 * // Gₙ = P2G(Pₙ)
 * mpm_transfer.P2G(particles, grid, &grid_data);
 * // compute Gₙ₊₁
 * TODO(zeshunzong): mpm_transfer.AddGravity(&grid_data);
 * // particle_data = G2P(Gₙ₊₁)
 * mpm_transfer.G2P(grid, grid_data, particles, &particles_data);
 * // update particles state except for position
 * mpm_transfer.UpdateParticlesState(particles_data, dt, &particles);
 * // afterwards we get Pₙ₊₁
 * particles.AdvectParticles(dt);
 * ```
 *
 * Implicit temporal advancement:
 * ```
 * mpm_transfer.SetupTransfer(&sparse_grid, &particles);
 * dG = ∞
 * while |dG|>ε:
 *   // Gₙ = P2G(Pₙ)
 *   mpm_transfer.P2G(particles, grid, &grid_data);
 *   // Solve the linear system H(Pₙ)⋅dG = -f(Pₙ)
 *   @note H and f depend on weights and particle deformation gradients
 *   TODO(zeshunzong): LinearSolve(H, f, Pₙ, &dg)
 *   Gₙ = Gₙ + dG
 *   // particle_data = G2P(Gₙ₊₁)
 *   mpm_transfer.G2P(grid, grid_data, particles, &particles_data);
 *   // Pₙ = UpdateParticlesState(particle_data)
 *   mpm_transfer.UpdateParticlesState(particles_data, dt, &particles);
 * end
 * // afterwards we get Pₙ₊₁
 * particles.AdvectParticles(dt);
 * Output Gₙ₊₁:=Gₙ, Pₙ₊₁:=Pₙ.
 * ```
```
___
*[`multibody/mpm/mpm_transfer.h` line 125 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB4jiK2WioZphqJ7 [...]

2024-01-02 23:39 UTC, xuchenhan-tri requested changes
I'll come back to the tests tomorrow.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28#-:-NnBXlhS6FbS-7Kor9GK:b-y408wg)* status: 8 of 14 files reviewed, 22 unresolved discussions (waiting on @zeshunzong)



<!-- Sent from Reviewable.io -->

2024-01-03 19:07 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: 8 of 14 files reviewed, 12 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAe87v8FYEfCGM47er:-NnBDzxWBaWiuSVqX_Vn:boxn1tr) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, the implementations should be in .cc files.
</blockquote></details>

todo added
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAeTVMBilkU1NWkS6w:-NnBJyrH3VdhpPquyJZg:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This really should be a DRAKE_DEMAND/ASSERT instead of an assignment. `Reset()` is in charge of setting the base nodes, and any other member function should not modify it.
</blockquote></details>

Done.
___
*[`multibody/mpm/mpm_model.h` line 14 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB0aQP-oHHP6wk5Xy3:-NnF_DO59Ai4vNFQPFTL:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This class needs some documentation. What would help me is some examples on how this class interacts with other classes. Just by looking at the set of APIs, this doesn't feel like a "model" but instead feels more like a mix between a "solver" and a "model". And I'm not sure what this class is trying to achieve in addition to what the `MpmTransfer` class is already capable of.
</blockquote></details>

Done.
___
*[`multibody/mpm/mpm_model.h` line 59 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAfXyU4rTuWWUvsLMv:-NnBExkV3Bn4I904Rlo_:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L59)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ultimately, gravity needs to be configurable. It's fine to hardcode for now if you want to focus on that later. Use -9.81 for the hardcode value.
</blockquote></details>

Done.
___
*[`multibody/mpm/mpm_model.h` line 62 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnBAVjZ4VFCKV2sn2vm:-NnF_A064iUSEqqWEIR4:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_model.h#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm finding it increasingly hard to reason through the mutable scratch data members you leave among different classes and the non-const member functions all over the place. It's hard to tell what are states, what are state-dependent data, and what are just temporary scratches. I wonder if there's a way to make those distinction clear.
</blockquote></details>

Done.
___
*[`multibody/mpm/mpm_transfer.h` line 70 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB8sF_5iddltNmDD8j:-NnF_4E_4YwfW2F0I2oE:bhv7sge) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_transfer.h#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

An updated pseudocode here might help me better understand the role of MpmModel and how it fits in the explicit/implicit scheme.
</blockquote></details>

put to the top of mpm_model.h
___
*[`multibody/mpm/mpm_transfer.h` line 130 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB4z1v-9fmlJpzPTLz:-NnF_-yS2tufau7QeDnE:b-n9tkhd) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/mpm_transfer.h#L130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, can you explain the intention behind the variable name? I don't see the `_all` suffix elsewhere. Is this parameter different than the other particle data that we pass around?
</blockquote></details>

changed
___
*[`multibody/mpm/pad.h` line 26 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAgHtXDQpeZXzFR2-O:-NnD7Qmt1nncWxDEWrwN:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/pad.h#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW consider `SetZero()` for a more descriptive name.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 22 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnB7xt3DD2z6IUjpVI8:-NnBOX-04x7bvW_Ba3g-:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No `using` statements in header files.
</blockquote></details>

Done.
___
*[`multibody/mpm/particles.h` line 95 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAz_mK5WLeCTyATCNm:-NnD4dZd8D8tYU-4Zwb9:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L95)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, why is PK stress an argument here? Shouldn't it be computed from the deformation gradient?
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 145 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAj7_sC4ldtB33M9Pm:-NnD6vBY2ABJgByBKlTV:b-k2kz15) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L145)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo,

Also, is this strictly true? I assume one doesn't need to call `Prepare()` every single time `SplatStressToP2gPads` is invoked in a newton loop, right?
</blockquote></details>

modified to be exact rn
___
*[`multibody/mpm/particles.h` line 390 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAkOys8W-d79jpgDvv:-NnD4kpg-T2gv0SCMO0z:bb2wjv6) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L390)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I thought we use `F_trial` to compute force and energy hessian in newton iterations? Please double check.
</blockquote></details>

you are correct
___
*[`multibody/mpm/particles.h` line 417 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAlP4938tjEN-fnUza:-NnBO3E9AjZGAODmCjBK:bss4a2b) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L417)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You definitely don't want to make a deep copy here each time this is called. Do you really need this getter?
</blockquote></details>

Removed.
___
*[`multibody/mpm/particles.h` line 456 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAloHD-ilE6E_iXBGX:-NnD4nmMEVdxQuWs4Nt_:bye62cq) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/particles.h#L456)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, where do you need this getter?
</blockquote></details>

in hessian, to be seen


<!-- Sent from Reviewable.io -->

2024-01-03 21:56 UTC, xuchenhan-tri requested changes
> Reviewed 1 of 3 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: all files reviewed, 9 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 86 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAc43U-69lsbCTQXA4:-NnFr1YC6MpoWMxJLFIV:bfhqmln) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/grid_data.h#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Not done?
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAeJ7OBE8ExVtMKVmn:-NnFrFDW6pxiljiBUxXO:bggqtdb) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

btw, a more common spelling would be:
</blockquote></details>

As a common review etiquette, please do not close a thread without either making obvious changes to the code addressing the comment or responding with why the recommended change is not taken. Otherwise, you leave the reviewer wondering if you actually read the comment.
___
*[`multibody/mpm/interpolation_weights.h` line 174 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAdpSPDiawULGcjyIp:-NnAdpSPDiawULGcjyIq:b-8rm7e8) ([raw file](https://github.com/zeshunzong/drake/blob/4df52eba2332c9df9661df9c585c18aa36437606/multibody/mpm/interpolation_weights.h#L174)):*
> ```objc
>           // (181).
>           particle_v_B_grad_v.grad_v +=
>               weighted_vi * weight_gradients_[idx_local].transpose();
> ```

This looks like a bug not caught by the existing unit tests. We should add a new test covering this.
___
*[`multibody/mpm/mpm_transfer.h` line 20 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnFsITR-xIfpYA6qoWU:-NnFsITR-xIfpYA6qoWV:bmunjzw) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/mpm_transfer.h#L20)):*
> ```objc
> template <typename T>
> struct TransferScratch {
>   // scratch pads for transferring states from particles to grid nodes
> ```

nit, it'd be nice to capture the semantic of the std::vector -- i.e. one pad per particle.
___
*[`multibody/mpm/particles.cc` line 33 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGB1PP5gNEixzmJRz3:-NnGB1PQApGdw2xhNfAL:b8x07kw) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/particles.cc#L33)):*
> ```cpp
>   PK_stresses_.emplace_back(P);
> 
>   PK_stresses_.emplace_back();
> ```

nit, surely this is unintended.
___
*[`multibody/mpm/test/mpm_model_test.cc` line 17 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGJ8Zi3lez-tLS2vz9:-NnGJ8Zi3lez-tLS2vzA:bb6smy4) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L17)):*
> ```cpp
> namespace {
> using drake::multibody::mpm::constitutive_model::CorotatedElasticModel;
> constexpr double kTolerance = 1e-10;
> ```

BTW, this is a pretty loose tolerance. Is this the tightest you can make it without failing the test. I wonder if this is caused by the SVD. Thoughts?



_Code quote:_
```cpp
constexpr double kTolerance = 1e-10;
```
___
*[`multibody/mpm/test/mpm_model_test.cc` line 18 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGIMXs8LumFrxHtzNh:-NnGIMXs8LumFrxHtzNi:bylkrip) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L18)):*
> ```cpp
> using drake::multibody::mpm::constitutive_model::CorotatedElasticModel;
> constexpr double kTolerance = 1e-10;
> constexpr int num_active_nodes = 63;
> ```

This number should be explained. As far as I can tell, this is not an arbitrary number and is determined by the configuration of the particles.
___
*[`multibody/mpm/test/mpm_model_test.cc` line 67 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGGhvi0SOyrNXdSuJb:-NnGGhvi0SOyrNXdSuJc:b-hy3j0z) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L67)):*
> ```cpp
>   particles.AddParticle(
>       Vector3<AutoDiffXd>(0.01, 0.01, 0.01), Vector3<AutoDiffXd>(0.0, 0.0, 0.0),
>       std::make_unique<CorotatedElasticModel<AutoDiffXd>>(1.0, 0.2), 1.0, 1.0);
> ```

nit, you should explain it's fine to have different constitutive models for different particles when you are explicitly making the assumption that all particles share the same constitutive model in your implementation. Ditto for your particles test.

BTW, I think you should properly support shuffling constitutive models instead of leaving a bug in the code as TODO.
___
*[`multibody/mpm/test/mpm_model_test.cc` line 102 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGImwM6BsYW64Ls42e:-NnGImwN52brOEgKzJ-Y:b-pu32ti) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L102)):*
> ```cpp
>     grid_velocities_input.push_back(Vi.col(i));
>   }
>   grid_data.velocities_ = grid_velocities_input;
> ```

nit, this is a red flag: a trailing "_" indicates that this is a data member of a class, but class should not expose private data member.



_Code quote:_
```cpp
grid_data.velocities_ = grid_velocities_input;
```


<!-- Sent from Reviewable.io -->

2024-01-03 22:55 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: 7 of 15 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/grid_data.h` line 86 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAc43U-69lsbCTQXA4:-NnGM44h4yV4XjziRiGb:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/grid_data.h#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

done
___
*[`multibody/mpm/interpolation_weights.h` line 147 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAeJ7OBE8ExVtMKVmn:-NnGMHlu0dyj7rvDUX2U:b-ua1eoa) ([raw file](https://github.com/zeshunzong/drake/blob/7457a3870fbb78fead5fab2e25eae8ccc7c72143/multibody/mpm/interpolation_weights.h#L147)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

As a common review etiquette, please do not close a thread without either making obvious changes to the code addressing the comment or responding with why the recommended change is not taken. Otherwise, you leave the reviewer wondering if you actually read the comment.
</blockquote></details>

changed but was reverted, forgot to check. done
___
*[`multibody/mpm/interpolation_weights.h` line 174 at r1](https://reviewable.io/reviews/zeshunzong/drake/28#-NnAdpSPDiawULGcjyIp:-NnGWrxzAzOc9o-4HDCH:becqz7l) ([raw file](https://github.com/zeshunzong/drake/blob/4df52eba2332c9df9661df9c585c18aa36437606/multibody/mpm/interpolation_weights.h#L174)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This looks like a bug not caught by the existing unit tests. We should add a new test covering this.
</blockquote></details>

done see transfer test
___
*[`multibody/mpm/mpm_transfer.h` line 20 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnFsITR-xIfpYA6qoWU:-NnGMXnl8fRbnD3AV-qM:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/mpm_transfer.h#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it'd be nice to capture the semantic of the std::vector -- i.e. one pad per particle.
</blockquote></details>

done
___
*[`multibody/mpm/particles.cc` line 33 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGB1PP5gNEixzmJRz3:-NnGMe3063Axd356hKJE:bbqubwd) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/particles.cc#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, surely this is unintended.
</blockquote></details>

done typo
___
*[`multibody/mpm/test/mpm_model_test.cc` line 17 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGJ8Zi3lez-tLS2vz9:-NnGNhz9EwIslT-P4xws:bt5pwh7) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this is a pretty loose tolerance. Is this the tightest you can make it without failing the test. I wonder if this is caused by the SVD. Thoughts?
</blockquote></details>

probably svd. I noticed before that F =diag(2,1,1) has a much smaller error, like 1e-16 or so
___
*[`multibody/mpm/test/mpm_model_test.cc` line 18 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGIMXs8LumFrxHtzNh:-NnGPGrH0PxubpYZnxo2:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This number should be explained. As far as I can tell, this is not an arbitrary number and is determined by the configuration of the particles.
</blockquote></details>

done
___
*[`multibody/mpm/test/mpm_model_test.cc` line 67 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGGhvi0SOyrNXdSuJb:-NnGMxT4BmKe3-b5n3c9:b-kzsc24) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L67)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, you should explain it's fine to have different constitutive models for different particles when you are explicitly making the assumption that all particles share the same constitutive model in your implementation. Ditto for your particles test.

BTW, I think you should properly support shuffling constitutive models instead of leaving a bug in the code as TODO.
</blockquote></details>

already supported, TODO was deleted but that commit was reverted. the test it is already on different models. 
Now the TODO is deleted!!
___
*[`multibody/mpm/test/mpm_model_test.cc` line 102 at r4](https://reviewable.io/reviews/zeshunzong/drake/28#-NnGImwM6BsYW64Ls42e:-NnGOpAB-KywXaHUkSfW:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd504a6b67d073e6c39b234c993600ae7e3a6740/multibody/mpm/test/mpm_model_test.cc#L102)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this is a red flag: a trailing "_" indicates that this is a data member of a class, but class should not expose private data member.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-04 18:44 UTC, xuchenhan-tri approved these changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 66 at r5](https://reviewable.io/reviews/zeshunzong/drake/28#-NnKmGtz2-g81BVcwnY_:-NnKmGtz2-g81BVcwnYa:b-vppubk) ([raw file](https://github.com/zeshunzong/drake/blob/bf79791b5a4e943d7e1cc41f630daf32e9038bf3/multibody/mpm/test/mpm_transfer_test.cc#L66)):*
> ```cpp
>   correct_grad_v(0, 0) = 2.0;
>   correct_grad_v(1, 1) = 2.0;
>   EXPECT_TRUE(CompareMatrices(particles_data.particle_grad_v_next[0],
> ```

nit, it should be noted that here we expect the gradv to be exact because quadratic bspline reproduces linear functions perfectly.


<!-- Sent from Reviewable.io -->

2024-01-04 18:44 UTC, xuchenhan-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28#-:-NnKmXy21ltCyqZAPnTk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)



<!-- Sent from Reviewable.io -->

2024-01-04 18:56 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 66 at r5](https://reviewable.io/reviews/zeshunzong/drake/28#-NnKmGtz2-g81BVcwnY_:-NnKp8eu1_rnCVX9RIsL:b-fovdzt) ([raw file](https://github.com/zeshunzong/drake/blob/bf79791b5a4e943d7e1cc41f630daf32e9038bf3/multibody/mpm/test/mpm_transfer_test.cc#L66)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it should be noted that here we expect the gradv to be exact because quadratic bspline reproduces linear functions perfectly.
</blockquote></details>

done added.


<!-- Sent from Reviewable.io -->

2024-01-10 17:13 UTC, xuchenhan-tri approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)



<!-- Sent from Reviewable.io -->

2024-01-10 17:13 UTC, merged