Add BSpline and AnalyticLevelSet
zeshunzong/drake pull request #7
Opened 2023-10-01 04:39 UTC by zeshunzong

2023-10-02 16:41 UTC, xuchenhan-tri requested changes
+@xuchenhan-tri 

FYI, use the above incantation to add the PR to my review dashboard.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7#-:-Nfl6yZvCcLTVzFmIHYV:b-t10cy7)* status: 3 of 7 files reviewed, 14 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/analytic_level_set.h` line 21 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7NqW6xJrSST362vg:-Nfl7NqW6xJrSST362vh:b-h461un) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L21)):*
> ```objc
> class AnalyticLevelSet {
>  public:
>   AnalyticLevelSet(double volume,
> ```

This constructor needs documentation. In particular, it's not immediately clear what the arguments do.

Also, it seems like this constructor should be protected instead of public.
___
*[`multibody/mpm/internal/analytic_level_set.h` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7gT28itMiasfKVcX:-Nfl7gT28itMiasfKVcY:b-m0liv6) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L24)):*
> ```objc
>                    const std::array<Vector3<double>, 2>& bounding_box);
> 
>   // Return true if the position is in the interiror of the level set.
> ```

https://drake.mit.edu/styleguide/cppguide.html#Function_Comments

FYI



_Suggestion:_
```objc
// Returns true if the position is in the interior of the level set.
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7z5AE0Gb_KqZrlv3:-Nfl7z5AE0Gb_KqZrlv4:b-rd7tl7) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L27)):*
> ```objc
>   virtual bool InInterior(const Vector3<double>& position) const = 0;
> 
>   // Return the outward unit normal of the interior of the analytic level set.
> ```

style. Ditto throughout this class.



_Suggestion:_
```objc
// Returns the outward unit normal of the interior of the analytic level set.
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 28 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl84Pc5COOB4p_xXho:-Nfl84Pc5COOB4p_xXhp:b-2ik74k) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L28)):*
> ```objc
> 
>   // Return the outward unit normal of the interior of the analytic level set.
>   // @throws exception if the position is outside of the geometry
> ```

FYI, style



_Suggestion:_
```objc
// @throws std::exception if the position is outside of the geometry
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 29 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflEACM3wRlcxIQuLpc:-NflEACM3wRlcxIQuLpd:b-91z2kl) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L29)):*
> ```objc
>   // Return the outward unit normal of the interior of the analytic level set.
>   // @throws exception if the position is outside of the geometry
>   virtual Vector3<double> Normal(const Vector3<double>& position) const = 0;
> ```

nit consider renaming.

We usually name functions as verb phrases (except for snake_case getters which are named the same way as data members).



_Suggestion:_
```objc
virtual Vector3<double> GetNormal(const Vector3<double>& position) const = 0;
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 32 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflB16n-h9q6Tx7EzcP:-NflB16n-h9q6Tx7EzcQ:b9juflb) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L32)):*
> ```objc
> 
>   // Return the volume enclosed by the level set
>   double get_volume() const;
> ```

BTW, there's a trend in our convention to name these snake case getters as `foo()` instead of `get_foo()`. Both are fine though.



_Code quote:_
```objc
get_volume()
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 46 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl8Pm8BqtAWlb-twcQ:-Nfl8Pm8BqtAWlb-twcR:bief660) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L46)):*
> ```objc
>   double volume_;
>   std::array<Vector3<double>, 2> bounding_box_{};
> };  // class AnalyticLevelSet
> ```

nit, style. Ditto throughout this file



_Suggestion:_
```objc
};
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 105 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl9BGU2SB3E8ykiZm3:-Nfl9BGU2SB3E8ykiZm4:b-es38br) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L105)):*
> ```objc
> };  // class BoxLevelSet
> 
> // An analytic level set class for right cylinder
> ```

nit, IIUC, this cylinder is centered at (0,0,0). If that's the case, it'd be nice to make that point explicit.



_Code quote:_
```objc
 An analytic level set class for right cylinder
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 117 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl9SzhEgb-I_OnuxuN:-Nfl9SzhEgb-I_OnuxuO:b-tfmpdz) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L117)):*
> ```objc
> // where r is the radius given, and z ∈ [-height, height].
> // For all interior points, the normal is defined as the vector from its
> // position to the closest point on the cylindrical surface (ignoring the lid).
> ```

This is a bit surprising to me. Does this mean that the normal at a point just slightly below the top lid (e.g. (0.1*radius, 0.1*radius, 0.9999*height)) has normal in the xy-plane, instead of (0,0,1)?



_Code quote:_
```objc
position to the closest point on the cylindrical surface (ignoring the lid).
```
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 10 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflAVMoAhZI3zSubDVi:-NflAVMoAhZI3zSubDVj:b-9y074n) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L10)):*
> ```cpp
> AnalyticLevelSet::AnalyticLevelSet(double volume,
>                             const std::array<Vector3<double>, 2>& bounding_box):
>                                 volume_(volume), bounding_box_(bounding_box) {}
> ```

nit, the formatting looks off.

If you run `bazel test ...` from `drake/multibody/mpm/internal` you should get a flurry of test failures from the linter and you should fix those.



_Code quote:_
```cpp
AnalyticLevelSet::AnalyticLevelSet(double volume,
                            const std::array<Vector3<double>, 2>& bounding_box):
                                volume_(volume), bounding_box_(bounding_box) {}
```
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 14 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflBGHf8LjBMzfBVV0b:-NflBGHf8LjBMzfBVV0c:b-qgud8i) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L14)):*
> ```cpp
> double AnalyticLevelSet::get_volume() const {
>     return volume_;
> }
> ```

BTW, this can be defined inline.

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions



_Code quote:_
```cpp
double AnalyticLevelSet::get_volume() const {
    return volume_;
}
```
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflC7IUB1mmsjmXYs6j:-NflC7IUB1mmsjmXYs6k:b-5cq6qa) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L27)): [...]

2023-10-02 18:02 UTC, xuchenhan-tri requested changes
I made a first pass. Looks great! Mostly nit comments.

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7#-:-NflXmin-uwtjP_VHYnJ:b-1d0ywu)* status: all files reviewed, 34 unresolved discussions (waiting on @zeshunzong)

*[a discussion](https://reviewable.io/reviews/zeshunzong/drake/7#-NflOyV0CCyEUv_ZYzNQ:-NflOyV0CCyEUv_ZYzNR:b-j9adtm) (no related file):*
minor, I think you can do away with the "internal" directory in `drake/multibody/mpm/internal`. We have a ton of internal namespace code and we don't usually have a "internal" directory.

___
*[a discussion](https://reviewable.io/reviews/zeshunzong/drake/7#-NflXtHN5NJClQJ_4Lez:-NflXtHN5NJClQJ_4Lf-:b11xi8g) (no related file):*
minor, for future references: we usually try to keep a single PR as small as possible to reduce the strain on reviewers. Typically we aim to limit the diff line to be below 750. Sometimes it's easier said than done. But in the case of this PR, you could have easily broken this down into a PR of Bspline and PR for level sets.

___
___
*[`multibody/mpm/internal/b_spline.h` line 23 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflQAPiEWV2v3Uxotcj:-NflQAPj5cSgTgDPeZre:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L23)):*
> ```objc
> class BSpline {
>  public:
>   BSpline(const T h, const Vector3<T>& position);
> ```

nit



_Suggestion:_
```objc
BSpline(const T& h, const Vector3<T>& position);
```
___
*[`multibody/mpm/internal/b_spline.h` line 30 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflQHQs2gtNJDmgOxsW:-NflQHQs2gtNJDmgOxsX:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L30)):*
> ```objc
>   BSpline();
> 
>   T get_h() const { return h_; }
> ```

nit



_Suggestion:_
```objc
const T& h() const { return h_; }
```
___
*[`multibody/mpm/internal/b_spline.h` line 31 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflQK2S5jwq0RY1pxZp:-NflQK2S5jwq0RY1pxZq:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L31)):*
> ```objc
> 
>   T get_h() const { return h_; }
>   Vector3<T> get_position() { return position_; }
> ```

nit



_Suggestion:_
```objc
const Vector3<T>& position() { return position_; }
```
___
*[`multibody/mpm/internal/b_spline.h` line 42 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflRGW881qwd73MvvDH:-NflRGW881qwd73MvvDI:bomx7zk) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L42)):*
> ```objc
>   T EvalBasis(const Vector3<T>& x) const;
>   Vector3<T> EvalGradientBasis(const Vector3<T>& x) const;
>   std::pair<T, Vector3<T>> EvalBasisAndGradient(const Vector3<T>& x) const;
> ```

BTW, The naming here is slightly odd to me.

I would call these `EvalValue`, `EvalGradient` and `EvalValueAndGradient` because BSpline is a function and it's natural to discuss its value and gradient.



_Code quote:_
```objc
std::pair<T, Vector3<T>> EvalBasisAndGradient(const Vector3<T>& x) const;
```
___
*[`multibody/mpm/internal/b_spline.h` line 48 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflU8wR6z8zFeGSykjg:-NflU8wR6z8zFeGSykjh:b-r4l42h) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L48)):*
> ```objc
>   // Bspline on the reference 1D domain r, note that the basis has compact
>   // support in [-1.5, 1.5]
>   T Eval1DBasis(T r) const;
> ```

BTW, I think the name of the function should emphasize this function acts on the reference domain. The fact that this is 1D is already clear from the parameter and the output.
So I would probably call this `EvalReferenceValue` or something similar. WDYT?



_Suggestion:_
```objc
T EvalReferenceValue(const T& r) const;
```
___
*[`multibody/mpm/internal/b_spline.h` line 49 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflR2MB9jh12sYB6ciC:-NflR2MC9O9aWhfLbNMD:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L49)):*
> ```objc
>   // support in [-1.5, 1.5]
>   T Eval1DBasis(T r) const;
>   T EvalGradient1DBasis(T r) const;
> ```

nit



_Suggestion:_
```objc
  // Helper function. Evaluates the values and the gradients of 1D quadratic
  // Bspline on the reference 1D domain r, note that the basis has compact
  // support in [-1.5, 1.5]
  T Eval1DBasis(const T& r) const;
  T EvalGradient1DBasis(const T& r) const;
```
___
*[`multibody/mpm/internal/b_spline.h` line 62 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflQpzf5POrLL6TZkHn:-NflQpzf5POrLL6TZkHo:b-v5p55k) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L62)):*
> ```objc
>                            // will have support [-1.5h, 1.5h]
>   Vector3<T> position_{};  // The "center" of the Bspline, or (xc,
>                            // yc, zc) in above comment
> ```

nit, do we need to autodiff these?



_Suggestion:_
```objc
  double h_{};                  // The scaling of the reference domain.
                           // Since the class is for the usage of
                           // MPM, we assume we are on the uniform
                           // grid, and the physical domain (x, y,
                           // z) can be transformed to the
                           // reference domain (r, s, t) through a
                           // affine transformation \phi^-1(x, y,
                           // z) = (r, s, t) = 1/h*(x-xc, y-yc,
                           // z-zc). The basis on physical domain
                           // will have support [-1.5h, 1.5h]
  Vector3<double> position_{};  // The "center" of the Bspline, or (xc,
                           // yc, zc) in above comment
```
___
*[`multibody/mpm/internal/b_spline.h` line 63 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflUXlS-La3BgWXqBia:-NflUXlS-La3BgWXqBib:bmqkarp) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.h#L63)):*
> ```objc
>   Vector3<T> position_{};  // The "center" of the Bspline, or (xc,
>                            // yc, zc) in above comment
> };                         // class BSpline
> ```

nit style



_Suggestion:_
```objc
};
```
___
*[`multibody/mpm/internal/b_spline.cc` line 30 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflT0iSAG2ilPaPCISE:-NflT0iSAG2ilPaPCISF:b-f0dnks) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.cc#L30)):*
> ```cpp
>   // If the basis is not in the support, we simply return 0.0
>   if (!InSupport(x)) {
>     return 0.0;
> ```

nit, do you need this predicate? I believe the "out of support" case is already handled by the `Eval1DBasis` function below.



_Code quote:_
```cpp
  if (!InSupport(x)) {
    return 0.0;
```
___
*[`multibody/mpm/internal/b_spline.cc` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflTIQt7oab9PRj6Ecb:-NflTIQt7oab9PRj6Ecc:b28jnas) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/b_spline.cc#L41)):*
> ```cpp
> Vector3<T> BSpline<T>::EvalGradientBasis(const Vector3<T>& x) const {
>   if (!InSupport(x)) {
>     return Vector3<T>(0.0, 0.0, 0.0);
> ```

nit, do you need this predicate? I believe the "out of support" case is already handled by the `EvalGradient1DBasis` function below.



_Code quote:_
```cpp
  if (!InSupport(x)) {
    return Vector3<T>(0.0, 0.0, 0.0);
```
___
*[`multibody/mpm/internal/b_spline.cc` line 65 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#- [...]

2023-10-03 17:01 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/zeshunzong/drake/7#-NflOyV0CCyEUv_ZYzNQ:-NfoTi2_6oCDUJjn6lhq:buhejdy) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I think you can do away with the "internal" directory in `drake/multibody/mpm/internal`. We have a ton of internal namespace code and we don't usually have a "internal" directory.
</blockquote></details>

noted, will do later

___
*[a discussion](https://reviewable.io/reviews/zeshunzong/drake/7#-NflXtHN5NJClQJ_4Lez:-NfoTnSI0t53aJjt0gUw:b-mx77kz) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, for future references: we usually try to keep a single PR as small as possible to reduce the strain on reviewers. Typically we aim to limit the diff line to be below 750. Sometimes it's easier said than done. But in the case of this PR, you could have easily broken this down into a PR of Bspline and PR for level sets.
</blockquote></details>

noted

___
___
*[`multibody/mpm/internal/analytic_level_set.h` line 21 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7NqW6xJrSST362vg:-NfmXa9B3s3ILMujZ1Ob:bci9bco) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This constructor needs documentation. In particular, it's not immediately clear what the arguments do.

Also, it seems like this constructor should be protected instead of public.
</blockquote></details>

take a look
___
*[`multibody/mpm/internal/analytic_level_set.h` line 24 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7gT28itMiasfKVcX:-NflvuC3DZd-WMS9YV1Y:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

https://drake.mit.edu/styleguide/cppguide.html#Function_Comments

FYI
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl7z5AE0Gb_KqZrlv3:-Nfm-08Z8qOWUTCKZI6E:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

style. Ditto throughout this class.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 28 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl84Pc5COOB4p_xXho:-Nfm--Bt50uTgA0USwns:b-7rl0kd) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L28)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, style
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 29 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflEACM3wRlcxIQuLpc:-NfmXYwYEb6cz3VI2e_0:b-7rl0kd) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit consider renaming.

We usually name functions as verb phrases (except for snake_case getters which are named the same way as data members).
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 32 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflB16n-h9q6Tx7EzcP:-Nfm-5KNCoCSZpf9UNt2:b-7rl0kd) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L32)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, there's a trend in our convention to name these snake case getters as `foo()` instead of `get_foo()`. Both are fine though.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 46 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl8Pm8BqtAWlb-twcQ:-Nfm-6UrBvgMkSoLvflj:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L46)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, style. Ditto throughout this file
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 105 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl9BGU2SB3E8ykiZm3:-Nfm2_vQ3wUCXPoVZ7On:b-7rl0kd) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L105)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, IIUC, this cylinder is centered at (0,0,0). If that's the case, it'd be nice to make that point explicit.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 117 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfl9SzhEgb-I_OnuxuN:-NfmXTVx2r_q8jYUUIS4:bc7qg9k) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.h#L117)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is a bit surprising to me. Does this mean that the normal at a point just slightly below the top lid (e.g. (0.1*radius, 0.1*radius, 0.9999*height)) has normal in the xy-plane, instead of (0,0,1)?
</blockquote></details>

change to a bona fide outward normal
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 10 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflAVMoAhZI3zSubDVi:-NfmXSFiCIhv2Zk5FxBe:b-7rl0kd) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the formatting looks off.

If you run `bazel test ...` from `drake/multibody/mpm/internal` you should get a flurry of test failures from the linter and you should fix those.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 14 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflBGHf8LjBMzfBVV0b:-Nflt4OkDYEKMgawVnpM:b-896fjx) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this can be defined inline.

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
</blockquote></details>

Done
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflC7IUB1mmsjmXYs6j:-NflvKhu2zxl330D-TNI:b-896fjx) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW I believe you could do
</blockquote></details>

Done
___
*[`multibody/mpm/internal/analytic_level_set.cc` line 32 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflCjMr-SEWNFJvG4YL:-Nfly6XQEEfRPPAZccAk:b-rnrbll) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/analytic_level_set.cc#L32)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The fact that points on the surface are defin [...]

2023-10-03 19:02 UTC, xuchenhan-tri requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7)* status: all files reviewed, 10 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/analytic_level_set.h` line 21 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfqo3hYCru7ZFPfHnWF:-Nfqo3hYCru7ZFPfHnWG:b-3b0ex5) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L21)):*
> ```objc
>  * A base class providing the interface of primitive geometries' level set in
>  * reference configuration
>  */
> ```

nit don't use doxygen comment in internal namespace. Only public functions outside of internal namespace get the doxygen treatment.

Ditto throughout this class.



_Suggestion:_
```objc
/* A base class providing the interface of primitive geometries' level set in
  reference configuration. */
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 36 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqpMLt24zbXgBQBdFc:-NfqpMLu9e0jFOg4Rwmi:b-1yi5wc) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L36)):*
> ```objc
>    * Returns the outward unit normal of an interior point at position in the
>    * analytic level set.
>    * @throws std::exception if the point is in exterior or on boundary
> ```

Do we really throw at the boundary?



_Code quote:_
```objc
* @throws std::exception if the point is in exterior or on boundary
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 40 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqoYCm6sJ0cKNBER8S:-NfqoYCm6sJ0cKNBER8T:bj1zcz2) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L40)):*
> ```objc
>   Vector3<double> GetNormal(const Vector3<double>& position) const;
> 
>   virtual Vector3<double> DoGetNormal(
> ```

This needs to be protected, not public.



_Code quote:_
```objc
 virtual Vector3<double> DoGetNormal(
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 68 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqozKqCfX1dGAdz_HD:-NfqozKqCfX1dGAdz_HE:bmumiw) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L68)):*
> ```objc
>   AnalyticLevelSet();
>   double volume_;
>   std::array<Vector3<double>, 2> bounding_box_{};
> ```

Data members should be private.

What you need here is a protected constructor that takes volume and bounding box as parameters.



_Code quote:_
```objc
 protected:
  /**
   * Creates an empty level set, with volume = 0 and bounding box = {[0,0,0],
   * [0,0,0]}
   */
  AnalyticLevelSet();
  double volume_;
  std::array<Vector3<double>, 2> bounding_box_{};
```
___
*[`multibody/mpm/internal/analytic_level_set.h` line 76 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqqBZP-LfvVSlKMmNt:-NfqqBZP-LfvVSlKMmNu:bz7nunp) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L76)):*
> ```objc
>  * normal) <= 0. e.g. in 2D, the half plane y>=0 should be defined by normal =
>  * (0,-1).
>  */
> ```

minor, a 2D example is irrelevant and potentially distracting.



_Suggestion:_
```objc
/* An analytic level set class for half space with the given `normal` and center
 (0, 0, 0). A point x is inside the (closure of) the half plane if
 dot(x, normal) <= 0. */
```
___
*[`multibody/mpm/internal/b_spline.h` line 33 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqsCsMBL8zM6GqFGDP:-NfqsCsMBL8zM6GqFGDQ:bjhz4yw) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/b_spline.h#L33)):*
> ```objc
>   const Vector3<double>& center() const { return center_; }
> 
>   T dummy(T x) { return 2.0 * x; }
> ```

minor, Remove



_Code quote:_
```objc
T dummy(T x) { return 2.0 * x; }
```
___
*[`multibody/mpm/internal/b_spline.h` line 45 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqsKgj9NIDRO22UyBq:-NfqsKgj9NIDRO22UyBr:b-6ui4sw) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/b_spline.h#L45)):*
> ```objc
> 
>   /**
>    * Computes {BSpline(x), ∇BSpline(x)}
> ```

nit, It's probably worth mentioning that calling this is more efficient that calling ComputeValue and ComputeGradient separately.



_Code quote:_
```objc
Computes {BSpline(x), ∇BSpline(x)}
```
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 34 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflWxQy-xu-nUpKB11E:-NfqtWZs2tTZn1MZmxsO:blambsg) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/test/b_spline_test.cc#L34)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

It looks like the default constructor still exist.
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 194 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfquS7_7uxkTWA3Me-H:-NfquS7_7uxkTWA3Me-I:b-qhzvho) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/test/b_spline_test.cc#L194)):*
> ```cpp
>   AutoDiffXd value1 = bs_ad.ComputeValue(point1_ad);
>   Vector3<double> grad_computed1 = bs.ComputeGradient(point1d);
>   Vector3<double> grad_autodiff1 = value1.derivatives();
> ```

BTW, instead of copypasting this function three times you can wrap this in a function or a lambda.



_Code quote:_
```cpp
  Vector3<AutoDiffXd> point1_ad = math::InitializeAutoDiff(point1d);
  AutoDiffXd value1 = bs_ad.ComputeValue(point1_ad);
  Vector3<double> grad_computed1 = bs.ComputeGradient(point1d);
  Vector3<double> grad_autodiff1 = value1.derivatives();
```
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 218 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfqtg8b10AvOTVpJWGW:-Nfqtg8c8jT3vMUiN8Vt:btb74v0) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/test/b_spline_test.cc#L218)):*
> ```cpp
>   // EXPECT_TRUE(1==0);
> 
>   // XPECT_EQ(der , grad1);
> ```

nit, delete dead code



_Code quote:_
```cpp
  // AutoDiffXd y = 1.1;
  // auto y_ad = math::InitializeAutoDiff(y)
  // AutoDiffXd z = bs.dummy(y_ad);
  // Eigen::VectorX<double> xxxx = (z.derivatives());
  // std::cout <<  xxxx(0)<< std::endl;
  // EXPECT_TRUE(1==0);

  // XPECT_EQ(der , grad1);
```


<!-- Sent from Reviewable.io -->

2023-10-03 21:07 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7)* status: all files reviewed, 10 unresolved discussions (waiting on @zeshunzong)

*[a discussion](https://reviewable.io/reviews/zeshunzong/drake/7#-NfrKCWY9GXhWa869sYQ:-NfrKCWY9GXhWa869sYR:bfylvq6) (no related file):*
FYI, In reviewable, there is the concept of disposition for a comment.

For comments starting "FYI", there's really no action item and it is indeed for your information.
Comments starting with "minor/nit" usually indicate that the issue isn't a major defect, but still needs to be fixed, and the reviewer believe the point is not contentious and expects the author to comply.
Comments starting with "BTW" indicate that there's no defect with the code, but the reviewer thinks there's a better alternative and it's the author's call to accept it or not.
All other comments indicate that the reviewer thinks there's a defect with the code and does not support the PR merging if the defect is not fixed.

___


<!-- Sent from Reviewable.io -->

2023-10-04 22:01 UTC, zeshunzong reviewed
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/analytic_level_set.h` line 21 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfqo3hYCru7ZFPfHnWF:-Nft8SH_2rZ_NfaRys20:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit don't use doxygen comment in internal namespace. Only public functions outside of internal namespace get the doxygen treatment.

Ditto throughout this class.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 36 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqpMLt24zbXgBQBdFc:-Nft8Tb4ESUGYrot3ciW:b4ax0f1) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L36)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do we really throw at the boundary?
</blockquote></details>

typo fixed
___
*[`multibody/mpm/internal/analytic_level_set.h` line 40 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqoYCm6sJ0cKNBER8S:-NftENlR7sQY84bEGHKU:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This needs to be protected, not public.
</blockquote></details>

done
___
*[`multibody/mpm/internal/analytic_level_set.h` line 76 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqqBZP-LfvVSlKMmNt:-Nft9Z3VCfsB-SXIujs6:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L76)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, a 2D example is irrelevant and potentially distracting.
</blockquote></details>

done
___
*[`multibody/mpm/internal/b_spline.h` line 33 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqsCsMBL8zM6GqFGDP:-NftNS0G1lUy7AWRyetl:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/b_spline.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, Remove
</blockquote></details>

done
___
*[`multibody/mpm/internal/b_spline.h` line 45 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqsKgj9NIDRO22UyBq:-NftNw7AB5dPGHq0g_VL:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/b_spline.h#L45)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, It's probably worth mentioning that calling this is more efficient that calling ComputeValue and ComputeGradient separately.
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 34 at r1](https://reviewable.io/reviews/zeshunzong/drake/7#-NflWxQy-xu-nUpKB11E:-Nfw-OJ25mR36mRZd62B:bss4a2b) ([raw file](https://github.com/zeshunzong/drake/blob/0fd695140810e4c4631bb5491126a8efdbef0b02/multibody/mpm/internal/test/b_spline_test.cc#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It looks like the default constructor still exist.
</blockquote></details>

Removed.
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 194 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfquS7_7uxkTWA3Me-H:-Nfw-yar7JnyFOR-vkYE:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/test/b_spline_test.cc#L194)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, instead of copypasting this function three times you can wrap this in a function or a lambda.
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/b_spline_test.cc` line 218 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-Nfqtg8b10AvOTVpJWGW:-NftO-k-1Wf5i04QQHzz:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/test/b_spline_test.cc#L218)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, delete dead code
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 23:07 UTC, xuchenhan-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/7#-:-NfwwWEO5myci16FqlhV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/analytic_level_set.h` line 68 at r2](https://reviewable.io/reviews/zeshunzong/drake/7#-NfqozKqCfX1dGAdz_HD:-Nfww8V48yAo4KP2kYBS:bb6un1j) ([raw file](https://github.com/zeshunzong/drake/blob/5e28794cc368fd28ecb48551a324a4e9c1761ba1/multibody/mpm/internal/analytic_level_set.h#L68)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Data members should be private.

What you need here is a protected constructor that takes volume and bounding box as parameters.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-04 23:57 UTC, merged